### ISSUE TITLE
Barrier client's can't connect to sever

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#1004]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/1004
> 
> Issue created on: 2021-01-06 by @PedroNestor2077
> Issue last updated on: 2021-05-04

i've be using barrier a long time, but this never happens

barrier client log: 
[2021-01-06T15:27:05] WARNING: failed to connect to server: No route to host
[2021-01-06T15:27:06] NOTE: connecting to '192.168.1.11*': 192.168.1.11*:24801
[2021-01-06T15:27:06] INFO: OpenSSL 1.1.1  11 Sep 2018

running barrier 2.3.3.2 on linux ubuntu 20.10 client and sever

please someone help me

---

> Commented on: 2021-01-06 by @albertony

Does the log say exactly that? How are you addressing the server? Hostname, IP, with/without port number? I'm wondering about the `'192.168.1.11*'`, not a valid address, and non-default port number 24801..

---

> Commented on: 2021-05-04 by @VNRARA

For ppl coming onto this issue later: Try disabling SSL in both client and server

---

> Closed on: 2021-01-07 by @PedroNestor2077

**Comment by HimBono** [comment]
Disabling SSL still does not work!
