### ISSUE TITLE
KDE is a very large dependency

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#1021]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/1021
> 
> Issue created on: 2021-01-11 by @RojjaCebolla
> Issue last updated on: 2021-06-13

Hey y'all, I already got Barrier working, so this is no big deal, but just a heads up:

I had barrier installed with `apt` on ubuntu, and it mysteriously stopped working one day. So I put up with it for a long time, I started sending myself messages over Signal when i needed to move something between computers A and B.

When I noticed that barrier is available on Flathub, I thought that was pretty cool, so I tried to install it. However, my HDD is almost all partitioned as `/home`, because prior to snap+flathub, 20 GiB is tons more space than I'll ever need for the root partition.  As you might imagine, having a few snaps & flatpaks on here means that there wasn't enough room for Barrier.  Barrier's not big at all, but that KDE dependency is half a gig or so.  Maybe qt would be good enough instead?

Ended up reinstalling Barrier the normal way so that i could `apt purge`, and then it worked fine upon re-reinstall.  So _I'm_ good to go for now. Just thought I'd pop in and say that Barrier is great, love using it, and I'd love to use the flatpak if it got a little smaller. Maybe other small-partition folks are out there too. 😁 

---

> Commented on: 2021-01-11 by @p12tic

@shymega Do you know whether it's us who maintain the flatpack package? I see stuff related to snap packaging in the source code.

---

> Commented on: 2021-06-13 by @shymega

@p12tic Sorry for the late reply. Catching up. I maintain it, Adrian transferred it to me. Adrian still has full control/ownership over the Snap, but I've been added as a co-maintainer to it.

**Comment by sithlord48** [comment]
With only a few runtimes to pick for building flatpaks and only one that provides Qt, We are stuck using the KDE one. I vote to close this bug, as we simply do not have another Qt containing  choice.

**Comment by shymega** [comment]
Agreed, yeah, this is a upstream Flatpak issue than our problem. Closing as wontfix.
