### ISSUE TITLE
[Question] Where are the task-bar icons located?

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#1122]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/1122
> 
> Issue created on: 2021-04-08 by @AllesMeins
> Issue last updated on: 2021-04-08

Admittedly this is a very unimportant question but since barrier is working flawlessly for me (thank you so much for that and all your work!), I've time to occupy myself with trifles. 

I'd like to create a monochrome barrier-icon for the taskbar/panel so it better fits my theme. But I just can't figure out where barrier stores those icons on a Linux system (I think they're called barrier-connected.png and barrier-disconnected.png). So could anybody put me in the right direction as to where I should put my monochrome icons so that they get picked up by barrier?

I'm running Kubuntu 20.04 with KDE Plasma 5.18.5

**Comment by shymega** [comment]
Icons have been changed, closing as outdated.
