### ISSUE TITLE
I can't to connect...

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#1138]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/1138
> 
> Issue created on: 2021-04-20 by @aleOS2
> Issue last updated on: 2021-07-09

Hi!
I tried this program, with my Linux PC, and my Windows 10 PC , and i want use my Linux PC keyboard and mouse
I don't know why is really really slowly to start my Barrier on Linux, and in the Log i receive:  WARNING: cannot listen for clients: cannot bind address: Address already in use

If i try to change my ip-address form the Barrier settings i receive: 2021-04-20T14:08:06] FATAL: failed to start server: cannot bind address: Cannot assign requested address
[2021-04-20T14:08:06] ERROR: process exited with error code: 1
[2021-04-20T14:08:06] INFO: detected process not running, auto restarting

How i can solve? Tranks! (If my english isn't perfect is because i'm Italian)

---

> Commented on: 2021-04-20 by @mmiszczyk

Cause of this problem is probably that the port is already in use. You can change the port on which Barrier is listening,but the real question is why exactly is this port taken, as it's not a common one. Maybe you have Synergy or a different version of Barrier running? Try using this command: ```netstat -lntp | grep 24800```.

---

> Commented on: 2021-04-20 by @aleOS2

tcp6       0      0 :::24800                :::*                    LISTEN      10670/barriers   

---

> Commented on: 2021-04-20 by @aleOS2

I have never  try this program or Synergy. I remember that in my first attemp it's work, but don't connect in my Windows PC, i restarted all two pc and i receive the error 

---

> Commented on: 2021-04-20 by @aleOS2

Can be is because i use 2.3.2-snapshot-210cb70 in Windows?  and the 2.3.2-snapshot-000000  in Linux?

---

> Commented on: 2021-04-20 by @aleOS2

Now in Linux i receive: [2021-04-20T14:49:23] INFO: starting server
[2021-04-20T14:49:23] INFO: config file: /tmp/Barrier.MycjNb
[2021-04-20T14:49:23] INFO: log level: INFO
[2021-04-20T14:49:23] WARNING: failed to register hotkey ScrollLock (id=ef14 mask=0000)
[2021-04-20T14:49:23] NOTE: started server (IPv4), waiting for clients   

---

> Commented on: 2021-04-20 by @aleOS2

and in WIndows: Note: Connecting to '192.168.178.102' 
Info: OpenSSL 1.0.21 25 May 2017
Failed to connect: Timed Out

---

> Commented on: 2021-05-05 by @danieltomasz

for someone in future who will have the same problem and will get running headless `barriers`
> tcp6 0 0 :::24800 :::* LISTEN 10670/barriers

`pidof barriers` and `kill` the process with given pid  

---

> Commented on: 2021-05-26 by @karlwilbur

When changing your IP address, it can get out of sync with the local Barrier settings config (`.config/Debauchee/Barrier.conf` on Ubuntu; this is not the same as the config file that is used to set your machine layout, `~/.barrier.conf` for me). You can edit the `Barrier.conf` file and change the ```interface=#.#.#.#``` value to match your new IP address.

In the GUI, you can access this settings screen at `Barrier -> Change Settings` or by pressing <kbd>F4</kbd>. On that screen,  you change the "Address" value (these settings values are what is stored in `.config/Debauchee/Barrier.conf`).

This is what I need to change when I modified my network to use a new class C network address. Once I updated that file, my server started up again. 

I also needed to configure my clients to use the new IP address for the server. I was able to SSH into the clients and update the same file (`.config/Debauchee/Barrier.conf`; `serverHostname=#.#.#.#` value), but needed to get to the connected keyboard and mouse to restart the Barrier client.

---

> Commented on: 2021-07-09 by @sevegee-tech

setup: 
Laptop 1 - Linux Mint 20.1
Laptop 2 - Linux Mint 20.1
Barrier installed (sudo apt install barrier); UFW - off

none of the answers above seem to address the problem - server-side log "ERROR: cannot listen for clients: cannot bind address: Address already in use"

Which address is already in use? Where is the conflict - how to resolve it?

thx

---

> Commented on: 2021-07-09 by @karlwilbur

@sevegee-tech, "Address already in use" means the port and IP address combination, not just the IP address. This will occur if you are configured to use the same port as another already-running application ....usually Barrier. This most commonly occurs when Barrier is already running and you try to start another instance. 

Use you favorite method of searching through running processes (I like `ps -eF | grep barrier`) and kill all existing Barrier processes, then try starting Barrier.

This is essentially the same solution provided by @danieltomasz above.

---

> Commented on: 2021-07-09 by @sevegee-tech

Thanks Karl... not sure where I'm going wrong here...
TOP; pidof barrier; killall -15 barrier... all return 'no running process'
but
ps -eF | grep barrier does list a process, just the one
kill pid returns ... 'no process'

reboot; now the server's waiting for clients; client-side times out, unable to connect.

confirmed the server-side config is using the correct client name
both laptops are on the same subnet and are visible to each other; ufw is off (both laptops)

---

> Commented on: 2021-07-09 by @danieltomasz

@sevegee-tech  maybe check the ports as described here https://github.com/debauchee/barrier/issues/190#issuecomment-444169720, here https://github.com/debauchee/barrier/issues/597, and here https://itsfoss.community/t/cannot-get-barrier-to-work/5012/34

also to check if the port isn't in use (as if the problem with address in use will come back)
```
sudo netstat -tlpn | grep ':24800'
``` 

---

> Commented on: 2021-07-09 by @sevegee-tech

netstat... server-side
tcp        0      0 192.168.178.54:24800    0.0.0.0:*               LISTEN      15131/barriers  
ping to client returns 6ms

Client-side... barrier connecting to server at 192.168.178.54 - timed out
                     ping 192.168.178.54 returns 6ms to that ip
                     nc -vz 192.168.178.54 24800 times out

So, I think that all confirms there's a client-side issue or, am I jumping the gun?

**Comment by shymega** [comment]
Closing as it seems the port is in use. Not an error with the software.
