### ISSUE TITLE
Trying to make a hotkey for Ctrl to Cmd on PC|Mac build.

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#1163]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/1163
> 
> Issue created on: 2021-05-14 by @Uzukii
> Issue last updated on: 2021-11-09

I want to be able to copy and paste in Mac OS with the same keys you do in Windows (Ctrl+C, Ctrl+V). The problem is Mac uses Cmd+C, Cmd+V and Windows doesn't have a Cmd key. It has the Win key in it's place. And the Win key can't be used as a modifier key in Barrier. So I can't make a Ctrl = Win or Ctrl+C, Ctrl+V = Cmd(Win)+C, Cmd(Win)+V hotkey.

---

> Commented on: 2021-05-20 by @serek2298

Its working this way by deafult in my case. Simply enable clipboard sharing.

---

> Commented on: 2021-05-20 by @Uzukii

There's clipboard sharing and then there's the convenience of being able to use the same physical key presses on the keyboard for Mac OS and Windows. I want to be able to press Ctrl+C and V in Mac OS to copy and paste, rather than  Win+C and V. Same goes for other hotkeys like Ctrl+A for select all.

---

> Commented on: 2021-05-20 by @lededev

You need read wiki.
https://github.com/debauchee/barrier/wiki/Command-Line#server_config

shift, ctrl, alt, altgr, meta, and super allow these keys to be mapped to a different key for that screen.

---

> Commented on: 2021-05-20 by @Uzukii

> You need read wiki.
> https://github.com/debauchee/barrier/wiki/Command-Line#server_config
> 
> shift, ctrl, alt, altgr, meta, and super allow these keys to be mapped to a different key for that screen.

Sorry, but I don't know what I'm looking at here. Where in the wiki does it tell you how to map the Ctrl key to the Cmd ⌘ key in Mac OS?

I know there's a way to remap keys in Mac OS itself but that doesn't work with keyboards connected through Barrier.

---

> Commented on: 2021-06-02 by @jbg

@Uzukii just below the section linked to above you will find https://github.com/debauchee/barrier/wiki/Command-Line#screen-options which shows how to solve your problem. "shift, ctrl, alt, altgr, meta, and super allow these keys to be mapped to a different key for that screen" -- I believe the cmd/windows key is `meta` but try it out and see.

---

> Commented on: 2021-11-09 by @owlwoopyto

@Uzukii I had this same question. In the server configuration settings, for my Mac client I set the Ctrl: modifier key to Super. Now when I press Ctrl+C on my keyboard, it copies text on the Mac. Hope this helps.

**Comment by shymega** [comment]
Closing as resolved.
