### ISSUE TITLE
I compiled barrier on android without root... x11 question

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#1184]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/1184
> 
> Issue created on: 2021-06-03 by @gregpalaci
> Issue last updated on: 2021-06-13

Basically I think there is a way to export the display of X11 but not sure the best approach here is where I'm at
![Screenshot_20210603_163254_tech ula](https://user-images.githubusercontent.com/1177690/120708571-ba4b6900-c489-11eb-9cff-c567aa3c7db1.jpg)

I've both installed the required xinit libaries I believe via https://askubuntu.com/questions/1256285/installing-xorg-without-gnome

Also I've tried https://play.google.com/store/apps/details?id=x.org.server&hl=en&gl=US
but I'm not sure what path vars to export etc

any tips? I can write out a guide for the rest of how to compile on android

---

> Commented on: 2021-06-13 by @shymega

The vars you really need for X11 are generally:

`XAUTHORITY` *and* `DISPLAY`. Maybe try that? If you can, please contribute a guide to the wiki (barrier-wiki.git repo, then I can merge into wiki), so others can benefit.

**Comment by shymega** [comment]
Closing as we don't currently support Android. And it's unlikely we will.
