### ISSUE TITLE
System requirements macOS

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#1195]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/1195
> 
> Issue created on: 2021-06-11 by @MM502
> Issue last updated on: 2021-09-29

I am trying to run Barrier on Mac OS X 10.9.5. The info.plist inside the package states that the minimum system version is 10.9.0. However, when I try to launch the Application I get the following:
`Crashed Thread:  0
Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000`

`Application Specific Information:
dyld: launch, loading dependent libraries`

`Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
  Referenced from: /Applications/Barrier.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
  Reason: image not found`

`Binary Images:
    0x7fff6381c000 -     0x7fff6384f887  dyld (239.5) <1D3130FE-FE7E-3C4C-8E74-EB51895B6BA5> /usr/lib/dyld
    0x7fff80dd2000 -     0x7fff80dd2fff  com.apple.ApplicationServices (48 - 48) <3E3F01A8-314D-378F-835E-9CC4F8820031> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff81a38000 -     0x7fff81a39ff7  libSystem.B.dylib (1197.1.1) <72A98ACC-7606-3AD5-82AF-02D4EBBD4F02> /usr/lib/libSystem.B.dylib
    0x7fff828b3000 -     0x7fff83429ff7  com.apple.AppKit (6.9 - 1265.21) <9DC13B27-841D-3839-93B2-3EDE66157BDE> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff83c6c000 -     0x7fff83cbefff  libc++.1.dylib (120) <4F68DFC5-2077-39A8-A449-CAC5FDEE7BDE> /usr/lib/libc++.1.dylib
    0x7fff8794a000 -     0x7fff87b2ffff  com.apple.CoreFoundation (6.9 - 855.17) <729BD6DA-1F63-3E72-A148-26F21EBF52BB> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
Crashed Thread:  0`

`Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000`

`Application Specific Information:
dyld: launch, loading dependent libraries`

`Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
  Referenced from: /Applications/Barrier.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
  Reason: image not found`

`Binary Images:
    0x7fff6381c000 -     0x7fff6384f887  dyld (239.5) <1D3130FE-FE7E-3C4C-8E74-EB51895B6BA5> /usr/lib/dyld
    0x7fff80dd2000 -     0x7fff80dd2fff  com.apple.ApplicationServices (48 - 48) <3E3F01A8-314D-378F-835E-9CC4F8820031> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff81a38000 -     0x7fff81a39ff7  libSystem.B.dylib (1197.1.1) <72A98ACC-7606-3AD5-82AF-02D4EBBD4F02> /usr/lib/libSystem.B.dylib
    0x7fff828b3000 -     0x7fff83429ff7  com.apple.AppKit (6.9 - 1265.21) <9DC13B27-841D-3839-93B2-3EDE66157BDE> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff83c6c000 -     0x7fff83cbefff  libc++.1.dylib (120) <4F68DFC5-2077-39A8-A449-CAC5FDEE7BDE> /usr/lib/libc++.1.dylib
    0x7fff8794a000 -     0x7fff87b2ffff  com.apple.CoreFoundation (6.9 - 855.17) <729BD6DA-1F63-3E72-A148-26F21EBF52BB> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation`

---

> Commented on: 2021-06-13 by @blexaer

Looking at the libraries it seems you will need El Capitan (macOS 10.11) or later for barrier to function, as this is the first version to support the Metal API.

---

> Commented on: 2021-09-29 by @Calorion

I'm running El Cap, but when I open it, I get an error saying to check with the developer to make sure Barrier works with this version of macOS. Indeed, the release notes for version 2.3.0 say "v2.3.0 requires macOS 10.12." So what is the most recent version that workes on 10.11?

**Comment by shymega** [comment]
@Calorion We no longer support v2.3.0 - v2.3.4 is the minimum you should use, due to a CVE in prior releases. Closing for now.
