### ISSUE TITLE
Mac OS X starting endlessly

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#125]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/125
> 
> Issue created on: 2018-09-06 by @iwoj
> Issue last updated on: 2020-11-13

### Operating Systems ###

Server: Mac OS X High Sierra

Client: Ubuntu 18

### Barrier Version ###

2.1.0

### Steps to reproduce bug ###

1. Setup Barrier as server
2. Click Start
3. Wait forever as it is stuck on "starting"

### Other info ###

* Does this bug prevent you from using Barrier entirely? Yes

---

> Commented on: 2018-09-06 by @OlivierChirouze

Same here

---

> Commented on: 2018-09-06 by @OlivierChirouze

Apparently I fixed the issue by just **naming** the client screen... Now Barrier server is starting (I'm still not seeing the second screen, but at least the application starts)

---

> Commented on: 2018-09-06 by @OlivierChirouze

Ok I got it working! Brillant piece of software.
I was just struggling because I couldn't have the "top left" position working for the client screen: only left or top position are working...

---

> Commented on: 2018-09-06 by @iwoj

This won't work for me. There's no client connected. 

---

> Commented on: 2018-09-07 by @nielspeen

@iwoj what does your barrier log say?

I had the same issue as @OlivierChirouze and had to add the screens using the exact names mentioned in the log.

---

> Commented on: 2018-09-08 by @walker0643

I'll add that exact names are required. The name of the client must match the name given to the server config for that screen.

---

> Commented on: 2018-09-10 by @OlivierChirouze

Sorry my reply was not complete: 

- **on the client side** I had to explicitly enter the IP of the server. I then opened logs, still on the server side, to verify that it was connected to server
- **on the server side** when configuring the screen disposition I had to name the client screen **just as it appears on the client side**.

There doesn't seem to be an "auto detect" feature on the server, you have to explicitly add clients by their own names.

---

> Commented on: 2019-01-20 by @ghost

There is no information on where the config files are stored, and that information is not on anything related to Barrier on the internet.

Where is the default config file?

---

> Commented on: 2019-01-20 by @AdrianKoshka

There is no default config file other than the settings in `barrier` -> `change settings`. The config files are generated as-needed during runtime for most unless you've specified a path to the config file.

---

> Commented on: 2020-11-13 by @paolocavagnolo

about the same configuration here:
barrier 2.3.3 - mac os high sierra as **Server** - ubuntu 20.04 as **Client**

same bug, solved by:
on Server, in configuration I add a new screen, named it as appear on the server barrier window, **moved the two screen on the top left**, one near the other

then it worked. thanks for the suggestion

**Comment by sithlord48** [comment]
Not a bug , User had not configured the server yet. Please close
