### ISSUE TITLE
keystroke

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#1311]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/1311
> 
> Issue created on: 2021-10-06 by @bgbruno
> Issue last updated on: 2021-10-06

### What happened?

I install app from #dmg for #macos
works perfectly

Q is any way how detect if something is "brought out" outside from computer - like keystrokes ?

### Version

v2.0.0

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

macos bigsur 11.6

**Comment by sithlord48** [comment]
Not a bug
