### ISSUE TITLE
Barrier not functional on cloud Virtual Machines on Azure or AWS

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#1313]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/1313
> 
> Issue created on: 2021-10-11 by @troublesprouter
> Issue last updated on: 2021-10-11

### What happened?

We have not managed to get Barrier to work or respond in cloud virtual machine environments in either Azure nor AWS.

Anyone know of a solution?

### Version

v2.3.3

### What OSes are you seeing the problem on? (Check all that apply)

Windows

### What OS versions are you using?

Windows 10

**Comment by shymega** [comment]
Closing due to lacking diagnostics. Can re-open once author provides further info.

cc: @@troublesprouter.
