### ISSUE TITLE
Barrier stopped working on macOS Catalina; assistive devices does not trust this process

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#1322]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/1322
> 
> Issue created on: 2021-10-18 by @Realinho
> Issue last updated on: 2021-10-18

### What happened?

Hello all,

Have been using Barrier for several months with no issues whatsoever, other than some difficulties getting some hotkey combinations to work (which I'm positive is related to the OS itself and not Barrier).

As of a few weeks ago, if I remember correctly right after a macOS update, Barrier stopped working. It launches successfully but keeps bouncing on the dock every half-second. Checking the log I notice that it's going through some sort of loop related to privacy settings.
I can confirm that I have added Barrier to the Accessibility and Input Monitoring sections under the Privacy tab of System Settings. Tried removing the entries and re-adding them, to no avail. Is it possible that it's looking for something else? 

### Version

v2.3.3

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

Catalina (10.15.7)

### Relevant log output

```shell
[2021-10-18T12:03:46] FATAL: An error occurred: assistive devices does not trust this process, allow it in system settings.
[2021-10-18T12:03:46] ERROR: process exited with error code: 1
[2021-10-18T12:03:46] INFO: detected process not running, auto restarting
```

**Comment by jinqiqiqi** [comment]
```bash
[2023-09-25T08:48:54] INFO: drag and drop enabled
[2023-09-25T08:48:54] FATAL: An error occurred: assistive devices does not trust this process, allow it in system settings.
```

That's what I've encounted after I running the below in terminal:
```bash
/usr/local/Cellar/input-leap/2.4.0-5+d30a509/InputLeap.app/Contents/MacOS/input-leaps -f  --debug INFO --name MBP.lan --enable-drag-drop -c ~/.config/input-leaps.conf -a :24800
```

Anybody can help with this?

**Comment by shymega** [comment]
Please don't hijack existing issues. This is a different issue you're experiencing - I would either ask on IRC, or open a new issue.

**Comment by gil** [comment]
I think I found a way to make it work. Go to "System Preferences" -> "Privacy & Security" -> "Accessibility" and click the plus button to add a new app to the list.

When finder shows asking you to pick the app, type cmd+shift+g and type `/Applications/InputLeap.app/Contents/MacOS/`. Then pick `input-leap` and give it access.

**Comment by mikehardy** [comment]
That is perfect @gil - thank you, the cmd+shift+g trick in order to go into the app bundle is key

🤔  I suppose the input-leap process itself needs to exercise the macOS "Am I trusted or not?" API and if not, it needs to request the permission by opening the accessibility pane? If it's not possible to directly request for that specific path then perhaps a dialog box that simply explains this workaround to the user, and then opens the pane?

**Comment by draeder** [comment]
I have this same issue on an M3 mini. The suggested workaround by @gil is not working. It is still stuck in "starting" when used as a server.

**Comment by tanimistiak** [comment]
yes. this workaround doesn't work anymore. and there is nothing in the given directory provided by @gil

**Comment by mikehardy** [comment]
I can't explain why it isn't working for you but I can say that this workaround is still working for me. I just upgraded from the 2.x series to 3.x and had to re-do the workaround, and it did work for me. Hopefully that's helpful just as a success report, in the sense you re-check and find something and it works for you. If not, condolences

**Comment by bleve97** [comment]
I had exactly the same issue, it just sat at "starting" (some nice debugging info would be helpful!) on an M1 mini after upgrading the M1 to macOS 15.2.  I had done all the permissions settings above, but nothing ... then, after about an hour, it just started working.  *shrug*

**Comment by shymega** [comment]
Closing as resolved.
