### ISSUE TITLE
Apple M1 - Barrier quits during sleep.

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#1355]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/1355
> 
> Issue created on: 2021-11-01 by @NYR99
> Issue last updated on: 2021-11-03

### What happened?

When I my Mac mini M1 with Monterey sleeps for the night, Barrier closes and I have to manually reopen it when I wake it up. 

### Version

v2.3.3

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

Monterery

---

> Commented on: 2021-11-01 by @DanielOberlechner

Hey @NYR99,
are you sure, that don't yourself created that problem somehow?
I use a Mac Mini M1 with Monteret aswell, and I never have any issues when i put the mac in the night on sleep.

Is the Mac the client or the server?
It closes on the Mac right?

Kind regards,
Daniel

---

> Commented on: 2021-11-01 by @NYR99

Mac is the server, a Windows 10 PC is the client. I have never had this problem with my intel iMac that I just replaced with the M1 mini, but if it goes to sleep overnight, in the morning Barrier is no longer running. I have to launch it again. If I sleep the Mac for only a few minutes, it works as intended. Seems only an issue when sleeping for a long period of time. 

---

> Commented on: 2021-11-02 by @tylerbenson

I see a similar problem on my m1 mac mini.  I go away for a while, I come back and barrier is no longer running.  Any suggestions for steps to troubleshoot?
(m1 mac mini - server, intel macbook pro client)

---

> Commented on: 2021-11-02 by @NYR99

I have confirmed that it is because of sleep. I disabled sleep for 24 hours and it’s been fine. 

---

> Commented on: 2021-11-03 by @juvin-git

i have the same problem

---

> Commented on: 2021-11-03 by @nickcharlton

I've been seeing the same. I'm running Monterey as the server, with the client being Windows 10. I am however using an Intel.

I think it's most likely related to Monterey going to sleep, rather than the M1.

**Comment by sithlord48** [comment]
This seams to be invalid running input-leap on M3 mbp that sleeps often and its not had to be restared once

**Comment by shymega** [comment]
Closing as resolved.
