### ISSUE TITLE
Installation of latest release fails on Windows 7 x32

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#139]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/139
> 
> Issue created on: 2018-10-01 by @krombel
> Issue last updated on: 2018-10-01

### Operating Systems ###
Win7 x32

### Barrier Version ###
2.1.0

### Steps to reproduce bug ###
1. Start installation
2. Run until the following error:
```
Unable to execute file C:\Windows\system32\sc.exe
CreateProcess failes; code 5. Access denied
```

### Other info ###
* Is there a way to work around it?
Not AFAIK
* Does this bug prevent you from using Barrier entirely?
Yes

**Comment by sithlord48** [comment]
Win7 is EOL for sometime, Please close
