### ISSUE TITLE
Android App?

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#1401]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/1401
> 
> Issue created on: 2021-11-05 by @shymega
> Issue last updated on: 2021-11-05

### Discussed in https://github.com/debauchee/barrier/discussions/1305

<div type='discussions-op-text'>

<sup>Originally posted by **RaghavRao** December  1, 2018</sup>
There seems to be an Android client for Synergy floating around (https://github.com/symless/synergy-android-7). I tried connecting to Barrier (and Synergy 1.10 Pro before I switched to Barrier) and I get this:
[2018-12-01T07:18:05] NOTE: accepted client connection
but nothing more.

This is probably too time-intensive to incorporate but would be nice to have if it's easy to integrate into the project linked above.

Thanks for making an awesome product!</div>

---

> Commented on: 2021-11-05 by @shymega

Oops, a duplicate issue exists. Keeping discussions for design ideas, issues for development, as before. A mistake on my part. Apologies.

---

> Closed on: 2021-11-05 by @shymega

**Comment by vriesj** [comment]
Link to duplicate issue https://github.com/input-leap/input-leap/issues/189
