### ISSUE TITLE
Rename all Barrier references to new project name

### ISSUE THREAD

**Issue by shymega** [input-leap/input-leap#1442]
This is a tracker issue of all progress, and therefore PRs/commits, in renaming
Barrier references to the new project name.

This should be completed as a prerequisite of the new release post-fork.

**Comment by shymega** [comment]
Hmm, would add this to both milestones, but can't seem to do that. I will move this to the Migration milestone, as it seems more related to that one.

**Comment by earthsound** [comment]
For the recent name changes ([pull 1438](https://github.com/input-leap/input-leap/pull/1438/files)), I think that instead of replacing the © 2018 Debauchee Open Source Group w/ © 2018 The InputLeap Developers, it's better to leave the 2018 copyright notice and add © 2021 The InputLeap Developers.

**Comment by shymega** [comment]
Yes, this is a good point. I had done a global `sed`, as there's so much code, but I will look into this. I think we should do that, and also, the `2018` was me being short-sighted.

**Comment by shymega** [comment]
@p12tic I propose that I revert b7a476f698e618be8f0e37df575220be1592f6a0, then we can work on a branch to fully rename the Barrier/Debauchee references, and make a PR for that. I think it's best to do it in a branch, and then make a PR, rather than multiple PRs.

Thoughts? It'll be a while on my end, unfortunately, due to other commitments.

**Comment by shymega** [comment]
@p12tic Did you see the above comment? I think we should still do a branch, and a recent Reddit post has noticed that we haven't decided on the final name for this fork, so we do need to make a decision, otherwise, it doesn't look as appealing as Barrier.

**Comment by shymega** [comment]
@p12tic We really need to decide on the final name. We have over 400 stars, and if we don't finalise the decision, I can see confusion becoming standard.

**Comment by earthsound** [comment]
Cross posting: I created [a poll in the Discussions area](https://github.com/input-leap/input-leap/discussions/1470) to vote for a name.

**Comment by shymega** [comment]
> > @p12tic We really need to decide on the final name. We have over 400 stars, and if we don't finalise the decision, I can see confusion becoming standard.
> 
> the name is confusing, I just compiled from git and was surprised to see the app installed as barrier and not input-leap

That's because we haven't finalized the name yet. The sources still refer to it as Barrier.

**Comment by abienz** [comment]
anecdotally I like the name input leap, and I'm a long time barrier user on Linux.

**Comment by shymega** [comment]
Done, closing.
