### ISSUE TITLE
The links from the readme point to the repository before forking.

### ISSUE THREAD

**Issue by akutoku** [input-leap/input-leap#1476]
### What happened?

All the links in the readme point to the old repository before the fork, not sure if that's your intended behavior, but to me it seems like you missed that.

### Version

From Git HEAD or commit (specify below)

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### What OS versions are you using?

n/a

**Comment by shymega** [comment]
Aware of this. There is a branch showing progress on this.

**Comment by shymega** [comment]
As you can see, there/s is now a PR, but things need to be added to the README again, I just removed them for now for speed.
