### ISSUE TITLE
Is Input-leap abandoned? 

### ISSUE THREAD

**Issue by myn** [input-leap/input-leap#1485]
### What happened?

I see no releases and the last commit was over a month ago. Is it safe to say input-leap is now abandoned?

### Version

v2.4.0

### What OSes are you seeing the problem on? (Check all that apply)

Linux, Windows, macOS

### What OS versions are you using?

OSX

**Comment by p12tic** [comment]
Lack of commits does not mean that the project is dead. As most open-source projects there is no one in InputLeap who's paid to work on it continuously, so commits happen whenever there is a problem that affects the maintainers themselves.

I agree that lack of releases is a problem, I personally just haven't had time to cut one.

I think I've answered the question, so I'll close the issue, but we can discuss in this comment thread afterwards.
