### ISSUE TITLE
Hotkey switch doesn't work on client when the host is using an alternative layout

### ISSUE THREAD

**Issue by kohend** [input-leap/input-leap#1528]
### What happened?

When setting a hotkey to switch between screens (I set the pause/break key), it switches to the client and back well when the server is in the default keyboard layout, but if the server is on a different layout (I used Hebrew), it's stuck on the client and I have to stop it to get back.

### Version

v2.4.0

### If applicable, where did you install Barrier from?

snap

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### What OS versions are you using?

Server - 22.04
Client - 20.04

### Relevant log output

```shell
[2022-12-15T09:31:21] INFO: switch from "srv" to "client" at 1645,68
[2022-12-15T09:31:21] INFO: leaving screen
[2022-12-15T09:31:24] INFO: switch from "client" to "srv" at 1297,623
[2022-12-15T09:31:24] INFO: entering screen
[2022-12-15T09:31:33] INFO: switch from "srv" to "client" at 1008,415
[2022-12-15T09:31:33] INFO: leaving screen
# several attempts to get back
[2022-12-15T09:31:59] NOTE: client "client" has disconnected
[2022-12-15T09:31:59] INFO: jump from "client" to "srv" at 960,540
[2022-12-15T09:31:59] INFO: entering screen
[2022-12-15T09:32:04] INFO: screen "srv" grabbed clipboard 1 from "client"
```

**Comment by kohend** [comment]
Switching via screen edge still works in this case.

**Comment by shymega** [comment]
This isn't from the Input Leap codebase - it's a snap, which means you're using Barrier, and they are two _separate_ codebases.

**Comment by kohend** [comment]
Currently there's no release of Input Leap, the tagged code should be identical, no?

**Comment by shymega** [comment]
No. It's not identical. We also do not provide a Snap, so this issue isn't necessarily reproducible on this codebase. I've updated the Issue template in response to the Barrier references.

**Comment by kohend** [comment]
The 2.4.0 tag is the same, I checked, should I compile from master and check if it reproduces?

**Comment by shymega** [comment]
You can, but I think it will still. I only closed because this was based on a Barrier snap, not an Input Leap Snap.

**Comment by kohend** [comment]
This is happening on the current master 68aac94193a721e4c20512434cf6ab40a2dd89a0 as well

**Comment by shymega** [comment]
Ah, OK. Interesting. We will look at your PR.
