### ISSUE TITLE
Corner Size GUI should allow values higher than 99

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#159]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/159
> 
> Issue created on: 2018-10-19 by @demonbane
> Issue last updated on: 2021-08-17

The Corner Size control in the screen settings and advanced server settings GUI looks like it's using the default QSpinBox settings which results in a limit of 99. This isn't very practical on high-dpi screens where 99 pixels in the corner is barely noticeable.

These controls should be updated with a higher [maximum](http://doc.qt.io/qt-5/qspinbox.html#maximum-prop) value to allow values above 99 to be entered without having to resort to manually editing a config file.

---

> Commented on: 2021-08-17 by @TheDiscordian

I just ran into this. I have a multi-monitor setup that wasn't working (Linux <-> Linux Monitor <-> MacBook), when I moved the mouse left of the MacBook, if it was too high or too low, it jumped all the way to the left-most monitor. Simply disabling corners and setting the size to 122 fixed my issue completely, works almost like a normal extended monitor now. A lot of people seem to run into multi-monitor issues, and I feel like simply fixing the UI here would go a long way.

**Comment by winreveng** [comment]
maybe you could make the textboxes also larger to reflect the higher numbers, on my windows even 2 digits do not really fit
