### ISSUE TITLE
suggest check for openssl version MacOS

### ISSUE THREAD

**Issue by rwcorbett** [input-leap/input-leap#1597]
### What happened?

suggest that check for openssl version ^3.*.* is made in `macos_environment.sh`

I encountered `fatal error: 'openssl/ossl_typ.h'` during build, but updating to v3 allowed full build. I fixed using brew `brew install opensll@3`

### Version

v2.0.0-RC1

### If applicable, where did you install Input Leap from?

self-build on MacOS - ran `clean_build.sh`

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

Ventura 13.2 - running on AppleM1 (not intel)

**Comment by shymega** [comment]
We don't support v2.0.0-RC1, let alone M1 yet. It should work via Rosetta, but it's not natively supported.

**Comment by shymega** [comment]
Instead of adding a check for OpenSSL v3 in the scripts, we should do it in CMake.

cc: @p12tic.
