### ISSUE TITLE
build fail - PopOS 22.04 - Could NOT find CURL

### ISSUE THREAD

**Issue by SteveDevOps** [input-leap/input-leap#1603]
### What happened?

Build fails, with error:
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:90 (message):
  Missing library: curl

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

68aac94

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### What OS versions are you using?

Pop!_OS 22.04 LTS x86_64

### Relevant log output

```shell
Build fails, with error:
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:90 (message):
  Missing library: curl
```

### Any other information

curl installed -- ver mismatch?

`curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd`

**Comment by shymega** [comment]
Invalid, you need to install the libcURL development headers. Closing.
