### ISSUE TITLE
Clang compatibility 

### ISSUE THREAD

**Issue by Lunarequest** [input-leap/input-leap#1615]
### What happened?

as it is now, input-leap will not compile if clang/clang++ is used instead of gcc/g++. So far a large amount of code spits out warnings and chunks of code just not compiling

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

8b547f92e919690ecefb33fa57ca4471b40c8a2f

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### What OS versions are you using?

```ini
NAME="openSUSE Tumbleweed"
# VERSION="20230228"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20230228"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20230228"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"
```

**Comment by shymega** [comment]
Is this fixed by #1616, @Lunarequest?

**Comment by Lunarequest** [comment]
There are a large amount of warnings I'd like to look into fixing

**Comment by shymega** [comment]
> There are a large amount of warnings I'd like to look into fixing

@Lunarequest I've compiled with clang++, and aside from my latest PR, it all compiles fine. What errors are you seeing?

**Comment by Lunarequest** [comment]
not errors but rather warnings about improper conversions and the such. I'd like to aim to remove all warnings produced by clang

**Comment by shymega** [comment]
OK, let's move forward with that goal in mind, then. Would you find it helpful if we had clang++ building Input Leap with `-Wall` and `-Werror`?

**Comment by Lunarequest** [comment]
I would find it helpful of we had a ci building with clang++ using `-Wall` and `-Werror`

**Comment by shymega** [comment]
Would `-Wextra` and `-pedantic-errors` be a requirement too? We need to refactor CI, it's a mess with libEI right now, and I don't like the way it's configured.

**Comment by Lunarequest** [comment]
> Would `-Wextra` and `-pedantic-errors` be a requirement too? We need to refactor CI, it's a mess with libEI right now, and I don't like the way it's configured.

For now no

**Comment by shymega** [comment]
I'm not seeing what you're seeing with clang. I only get `-Wunused-private-field`, no improper conversions. What CXXFLAGS are you passing?

**Comment by shymega** [comment]
@Lunarequest Following up on this. Can you confirm the `$CXXFLAGS` variable you pass?

**Comment by shymega** [comment]
@Lunarequest I would like to fix clang builds in v3.0.0. However, I haven't heard from you about the `CXXFLAGS` variable, and I can't fix the issues without this. If you have a moment, could you advise?

**Comment by Lunarequest** [comment]
my bad, it was an issue with my distros clang not with Barrier, In the future we should treat the warnings as errors and see if its possible to resolve the warnings.

**Comment by shymega** [comment]
@Lunarequest Thank you for replying. We are making CI build on clang, and I don't think we'll be treating warnings as errors.
