### ISSUE TITLE
ice and sm packages not found

### ISSUE THREAD

**Issue by Khazad-C** [input-leap/input-leap#1619]
### What happened?

Hi, i'm trying to build input-leap on Fedora 37 (KDE), i followed the steps in the wiki but when i run "./clean_build.sh" shows some errors related to missing packages.
In specific, the packages are "ice" and "sm", i tried to reinstall everything from the previous steps and even install ice package from X, but nothing changed.

Here is the error:
![ice_sm_pck](https://user-images.githubusercontent.com/94282854/223187823-1707affc-9dbc-4f11-b369-63bc9e6a5567.png)

I must say i'm completely new in this kind of stuff (new on programming, linux and git projects) so maybe i'm not seeing something obvious.

### Version

v2.4.0

### If applicable, where did you install Input Leap from?

Wiki guide from this repository

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### What OS versions are you using?

Fedora 37 KDE

**Comment by shymega** [comment]
Reopening, this needs to be edited on the wiki. It may be fixed for you, but it's not for us.

**Comment by Khazad-C** [comment]
> Reopening, this needs to be edited on the wiki. It may be fixed for you, but it's not for us.

Sorry! my bad. Also i was able to fix it. 
Had to install  libICE-devel   libSM-devel  and after that other package was missing "qt5-qttools", so installed qt5-qttools-devel too.
After installing those packages, i was able to build the project without any trouble.

**Comment by shymega** [comment]
@Khazad-C Thanks, I've pushed a fix to the wiki. Also removed the pre-Fedora 35 instructions, to keep the wiki modernised and simple. Closing now. We had to add Xinerama and XRandr devel packages.

**Comment by kaovilai** [comment]
Want to note that these instructions work on F39 for me
