### ISSUE TITLE
MacOS icons

### ISSUE THREAD

**Issue by vancluever** [input-leap/input-leap#1641]
### What happened?

Looks like the icons were updated recently - looks nice!

Looks like the MacOS icon set (located at `dist/macos/bundle/InputLeap.app/Contents/Resources/InputLeap.icns`) still needs updating though. This affects the app and dock icons.

Happy to take a stab at building the file if I could be pointed to all of the resolutions needed. 

Mozilla has some info about building the iconset for Firefox here: https://firefox-source-docs.mozilla.org/browser/branding/docs/UpdatingMacIcons.html

Looks like the old .icns file contains the following resolutions:

* 1024*1024
* 512*512
* 256*256
* 32*32
* 16*16

PS: Seems like there's another .icns file at `src/gui/res/mac/QInputLeap.icns` but I don't know what it's used for.

### Version

From Git HEAD or commit (specify below)

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

MacOS Ventura

**Comment by shymega** [comment]
What info on the resolutions do you need? I'm not sure I follow, given you listed them.

Thanks for the heads-up!

**Comment by vancluever** [comment]
@shymega the icons would need to be generated from an asset suitable for scaling, so a high-quality source would be good. I was hoping that yall could just provide the source images at the resolution and I'd bundle them, but someone else could do it too if they had a mac that they could run iconutil from and the appropriate image(s). Was just offering in case access to an appropriate Mac was not easy.

**Comment by shymega** [comment]
@vancluever Only thing that comes to mind is this: https://github.com/input-leap/input-leap/pull/1618

Would that SVG work? I don't have a Mac (I have way too many computers, but I am streamlining.. slowly...), so I can't do it.

**Comment by vancluever** [comment]
@shymega now added in #1666. Also I was able to do this 100% on Linux using ImageMagick and [libicns](https://icns.sourceforge.io/), in case it needs to be updated in the future!

**Comment by shymega** [comment]
@vancluever Awesome, thank you! Great to have someone active who can/does help out with macOS. Merged.
