### ISSUE TITLE
Modifier keys stuck on the connected screen PC

### ISSUE THREAD

**Issue by project-administrator** [input-leap/input-leap#1690]
### What happened?

After some time of using the input-leap (several hours, maybe it's related to xscreensaver unlock) modifier keys like CTRL/SHIFT/ALT tend to get "stuck" on one of the connected screens. Moreover, when this issue occurs the keys are also stuck on the physical keyboard of the connected screen as well. 

By "stuck" I mean this behavior as an example when I try to type keys on input-leap server or even the physical keyboard directly connected to the affected screen: 
- hitting the "TAB" key triggers the "Alt-Tab" app switcher and does not quit from the app switcher as if I'm still holding the "Alt" key (which I did not touch at all)
- most of the alpha-numeric keys cannot be typed
- hitting the key"3" results in "#" typed
- hitting the key "4" two times results in "TAB" key pressed

Depending on which keys are "stuck" you'll get different behavior, but it's always annoying and unusable.

When this issue happens on one of the connected screens, other screens are usually not affected, i.e. I'd say it's the input-leap client issue. 

Even exiting from input-leap on the connected screen and the server does not resolve the issue on the connected screen. I mean, you are not even able to use the physical keyboard connected directly to the affected screen after that. Looks like this issue modifies the input behavior of the X11 server and the workaround would be to re-login (or reboot). 

Another work-around to fix the connected screen is to switch to the text console with CTRL+ALT+F1 on the physical keyboard and run the following:
```
$ sleep 10; DISPLAY=:0 bash screen_fix.sh
$ cat screen_fix.sh
#!/usr/bin/env bash

echo Running stuck keys fix
#setxkbmap -layout us
xdotool keyup Shift_L Shift_R Control_L Control_R Alt_L Alt_R Super_L Super_R Hyper_L Hyper_R Caps_Lock 204 205 206 207
echo Complete
```
Then switch back to your screen (usually with CTRL+ALT+F7)

I tried toggling these options for the connected client, but they don't seem to have any effect on this issue:
- "Fix XTest for Xinerama"
- "Fix Preserve Focus"

I had similar issues with barrier and synergy.. Tried input-leap but the issue is still there. 

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

004a54fb

### If applicable, where did you install Input Leap from?

self-built executables

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

X11

### What OS versions are you using?

Debian/Ubuntu 22.04

**Comment by shymega** [comment]
Hey, thanks for opening this bug report.

I just wanted to say a huge thanks, for the way you filed this bug report. You gave the info we need, bug reproduction details, and environment information, and it really makes a difference. It's not often we get bug reports like this, hence the praise. Makes all the difference.

**Comment by gui-mi** [comment]
Have the same problem betweeen Windows 10 (22H2) acting as server with Barrier v2.4.0-release-3e0d758b and a Linux Mint 21.3 5.15.0-91-generic kernel X11 with the same Barrier version installed via flatpak.

**Comment by shymega** [comment]
@gui-mi Whilst this is useful to know that Barrier suffers from the same bug, we don't support Barrier on this project. Users should keep Barrier-related bug reports/confirmations *to the Barrier project* only.

I'm not going to hide your comment on this occasion, but please bear this in mind.

**Comment by gui-mi** [comment]
Sure I understand. Just thought that I could provide a bit more information about the bug.

**Comment by TechnicalMonkey** [comment]
I'm sorry for this answer more than two years after the issue opened, but i thought if anyone new would see this and also be confused as to why the provided commands don't work i hope to help them with this comment.

So the bug i found is that if you have the key pressed while switching somehow to the client or the server(in my case it was the client with the meta-key) the pressed key gets "stuck" (for me L meant log out, E meant explorer and so on). Solve this go to the side where the keyboard still acts "normal" and press the key that is "stuck" and then switch again. This fixed it for me.
