### ISSUE TITLE
CI should build 'Debug' macOS binaries for users to test.

### ISSUE THREAD

**Issue by shymega** [input-leap/input-leap#1703]
#1629 (created by @Cimbali) was merged recently by @shymega, and currently, it's not uploading macOS DMGs for Debug builds.

Some users have expressed interest in downloading Windows binaries, for testing or immediate usage on their systems.

At the moment, we haven't released v3.0.0, so there's no Windows installers, or macOS DMGs.

Concordantly, this leaves out macOS users who wish to test Input Leap on their Mac devices.

I would like to propose we refactor the conditional here[0] to allow for DMG uploads on macOS builders.

@p12tic: I'm aware you were working to incrementally merge #1629, but recently, there was a tense discussion on the repository regarding CI/CD, and I had to do something to provide some degree of pre-built binaries. #1629 took too long to merge.

I think there's a few more things we can improve on with CI, and if we need to, #1629 could be reverted, and then cherry-picked and merged back in with your changes, but we had to get on with merging at the time.

@Cimbali: I have one more issue I plan to make regarding CI, which is regarding Ubuntu 18.04.

**Comment by Cimbali** [comment]
Essentially you want to add installers for the macOS debug builds? That’s really just dropping the `if` conditional on the dmg upload step, i.e. remove line 203 in this block:

https://github.com/input-leap/input-leap/blob/293e2585effb70d6b81c5694ac34802c76b71d8a/.github/workflows/builds.yml#L201-L208

Might need a small rename on the upload name to disambiguate between builds.

**Comment by shymega** [comment]
Yes, I think we're working towards Universal Binaries currently, but will bear this in mind. Cheers.

cc: @sithlord48
