### ISSUE TITLE
input-leap not working in gdm3 wayland

### ISSUE THREAD

**Issue by prahal** [input-leap/input-leap#1708]
### What happened?

When copying input-leap client setup to gdm3 home folder, with gdm Xorg input-leap takes effect but not with gdm wayland.
The same is also true of gdm3 wayland as input leap server.
Could be there is not xdg portal support in gdm as I am not even asked for authorization from an xdg popup.
With the the same setup after gdm login input-leap works in the gnome-shell 45 wayland session.

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

4ecedf1d758

### If applicable, where did you install Input Leap from?

git

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Wayland.

### What OS versions are you using?

Debian trixie

### Relevant log output

```shell
oct. 10 08:45:43 cyclope /usr/libexec/gdm-wayland-session[3068]: gnome-session-binary[3068]: DEBUG(+): GsmAutostartApp: starting input-leap.desktop: command=input-leap -f --no-tray --debug INFO --name cyclope --enable-crypto hermes.prahal.homelinux.net:24800 startup-id=10d03d20699c1fd8a2169692753560890600000030680016
oct. 10 08:45:43 cyclope gnome-session-binary[3068]: DEBUG(+): GsmAutostartApp: started pid:4827
oct. 10 08:45:43 cyclope gnome-session-binary[3068]: DEBUG(+): GsmManager: starting app '/org/gnome/SessionManager/App17'
oct. 10 08:45:43 cyclope gnome-session-binary[3068]: DEBUG(+): Starting app: /org/gnome/SessionManager/App17
oct. 10 08:45:43 cyclope gnome-session-binary[3068]: DEBUG(+): GsmAutostartApp: starting input-leap.desktop: command=input-leap -f --no-tray --debug INFO --name cyclope --enable-crypto hermes.prahal.homelinux.net:24800 startup-id=10d03d20699c1fd8a2169692753560890600000030680016
(...)
oct. 10 08:45:44 cyclope input-leap.desktop[4832]: QSocketNotifier: Can only be used with threads started with QThread
(...)
oct. 10 08:45:57 cyclope input-leap.desktop[4832]: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
```

**Comment by shymega** [comment]
I don't think this is a bug. Input Leap isn't designed to work this way.

**Comment by prahal** [comment]
@shymega you mean we are not supposed to login to a client via input-leap?

This is a real shortcoming as my use case is a laptop plugged into an external display and is supposed to stay with its lid closed, thus no access to its keyboard.
My aim was to use a single keyboard for a desktop with its keyboard and a second display for the laptop with most of the time the laptop closed, using the desktop keyboard.

If I cannot log in this becomes an annoyance, while not a complete showstopper. I can still open, log in with the laptop keyboard then close the laptop. The most annoying is I have to move my chair to access the laptop keyboard.

gnome-shell handles such an external display with the laptop lid closed as the default laptop with external monitor behavior, that is it does not suspend when an external display is connected to a laptop and the lid is closed.

input-leap handles gdm by copying the setup (config and SSL cert) for the user login session to the gdm3 home (/var/lib/gdm3 on Debian). Indeed quite hackish.

Still, I wonder if xdg portal is the right access tool for input-leap. I mean input-leap access is system policy to me, not user session policy. Do we really want the user in control of the input-leap access, not the administrator?

Under Windows, input-leap is working under the login manager. I cannot test on Mac OS.

In fact, I expect even to be able to access the client login manager from a server login manager (gdm3 Wayland to gdm3 Wayland).

Feel free to close this bug if it is not in the scope of the project (and obviously the behavior on the Windows login manager is an undefined behavior).

**Comment by prurigro** [comment]
Can you setup gdm to auto-log you in + start input-leap? You could then use input-leap to unlock the keyring.

**Comment by prahal** [comment]
@prurigro I cannot, this is a laptop I use remotely. Disabling login would be opening the box to anyone.
There are also network passwords and private keys on the box.
That would be a worse security issue than enabling input-leap to control my gdm session from a box I trust without the client box user acknowledging the access, which is what libportal is all about.

I don't see the point in enforcing xdg portal to give access to the Wayland session if I have to remove all authentication to access the session.

Agreed that it might work in an environment where you do not care at all about security and have no secrets in the user session.

**Comment by prurigro** [comment]
If the passphrases/for your private keys and passwords are locked in gnome-keyring, that won't get unlocked with auto-login (it'll prompt you the first time the keys get used), and if your disk is encrypted you're already submitting to a challenge prior to the laptop being in a usable state (if neither of those things are true, someone could pull the SSD out of the laptop and read your files directly).

That said, I agree that it isn't the most ideal scenario, it's probably your best bet if you want to avoid needing to log in manually though since gdm is running a separate session from your desktop (it even has its own user, home directory and separate dconf settings).

Another option could be to look at PiKVM for the initial login, but that might also be overkill lol.

**Comment by prahal** [comment]
@prurigro my issue is not with manual login but with manual login from the physical keyboard of the client instead of the input-leap server. I want to enter the password in gdm on the input-leap client but with the input-leap server box keyboard.

If I leave for a few minutes it is not doable to remove the 10 screws to access my hard drive which is itself screwed to a tray.

Disk encryption would not secure anything if the session autologin. Then the disk encryption is required to auto unlock too. It is way easier to steal my whole laptop and let it autologin than extract the HDD.

The ssh private keys are in the home folder. Once autlogin nothing can prevent their access. This also bypasses all the permission schemes for all other files any of which might be private.
I do not store the password from my private keys at all. But I really doubt this is this hard to brute force a private key password with johntheripper once you have the private key file.


This use case is working with all other platforms. If you remove access to Windows or OSX login manager I doubt a lot of users would find it practical. Is it really out of the scope of input-leap to be able to log in on the input-leap client from the input-leap server?

Also initially my laptop was mounted on an arm rendering typing on the physical keyboard very hard. For now, it is back on the table as I use the arm for a second screen. Also, any arms for laptops have covers over the keyboard that render it impossible to type at all.

**Comment by Findarato** [comment]
Can you login to it remotely using remote desktop and then make sure it is started?

**Comment by shymega** [comment]
You can't do it this way. Unix/Linux/BSD works differently. The display manager - i.e., the login screen - runs as its own user. 

Input Leap on Wayland, and X11, relies on user-owned facilities to manage the session, and this can't be worked around. I will close this issue for now, because it's outside our scope, and wouldn't be technically feasible without causing breakage.

Please discuss this further in the Discussions tab.

Thank you.

**Comment by cobowers** [comment]
I also need this. Using GDM/Wayland, I have created an entry in /usr/share/gdm/greeter/autostart/inputleap.desktop to simply launch /usr/bin/input-leap.c with the necessary parameters to connect to the host. I can verify that the process is running and connected, but can't move into the client GDM screen from the server. I suspect that it simply needs remote permission, but there is no popup in GDM. This all works as expected in GDM Xorg.

**Comment by shymega** [comment]
We've already established this isn't possible, and I've explained why. 

Please refrain from commenting on this issue with the same request - from the way Input Leap currently works, this isn't possible.
