### ISSUE TITLE
Binding input to one screen does not work on Wayland

### ISSUE THREAD

**Issue by ixevix** [input-leap/input-leap#1711]
### What happened?

Running `/usr/bin/input-leaps -f --no-tray --debug INFO --use-ei --name foobar --disable-client-cert-checking -c /home/ixevix/.config/barrier/synergy_server_dump3.conf --address :24800` on GNOME Wayland session. I'm connecting from Windows 10 VM and to my surprise it seems to work. However the feature that I'm using to lock the input to either the host or VM doesn't seem to work. In my config section: options I have
`keystroke(Control+BackSpace) = lockCursorToScreen(toggle)` and I tried with that and without that and neither works. Noting here that running on X11 it works. Noting here also that I saw some comment that multiple displays don't work on Wayland yet so I had only one screen on the host while testing this.

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

edaa634551eb530a4ae6eaf1d31d62a72d70c961

### If applicable, where did you install Input Leap from?

I've built input-leap for wayland including input-leap-git, libportal-inputcapture, xdg-desktop-portal-git, xdg-desktop-portal-gtk-git and xdg-desktop-portal-gnome-git. All packages from AUR on archlinux except libei which is from extra v1.1.0-1.

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Wayland

### What OS versions are you using?

Archlinux running GNOME 45 and kernel 6.5.7-arch1-1.

**Comment by shymega** [comment]
This is likely missing scaffolding for the `libei` backend. I know the libportal interfaces can support regions, so we'll need to extend that with Input Leap's built-in functionality.

cc: @whot

**Comment by whot** [comment]
Regions are actually the equivalent of monitors which in this case is a different thing, right? This is about the cursor not moving to the respective other host when the lock is enabled?

**Comment by ixevix** [comment]
> Regions are actually the equivalent of monitors which in this case is a different thing, right? This is about the cursor not moving to the respective other host when the lock is enabled?

This is about the lock not preventing moving the cursor between hosts.

**Comment by whot** [comment]
Confirmed as simply missing, `EiScreen.cpp` needs the equivalent to `onHotKey()` that the other screen implementations have.
