### ISSUE TITLE
GUI cannot run in native Wayland-only session

### ISSUE THREAD

**Issue by darkblaze69** [input-leap/input-leap#1792]
### What happened?

GUI cannot run in native Wayland-only session

* run in `gnome-shell --no-x11` session or `DISPLAY= input-leap`
* it says `The InputLeap GUI requires the DISPLAY environment variable to be set. Quitting...`

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

3e68145

### If applicable, where did you install Input Leap from?

from source

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Wayland

### What OS versions are you using?

Arch Linux, GNOME 45.1

### Any other information

I've locally removed the code checking for Xwayland, and it runs in wayland-only just fine in both client and server, so IIUC there's no need for such checking nowadays.

**Comment by shymega** [comment]
Can you provide a diff of your changes? What commit did you base your changes on?

**Comment by darkblaze69** [comment]
I based on latest `master` e.g. 3e681454b737633a70f2f3b789046a5cb1946708

as per https://github.com/input-leap/input-leap/issues/109 I also installed latest libportal from `main`.

[xwayland.txt](https://github.com/input-leap/input-leap/files/13536343/xwayland.txt)

**Comment by shymega** [comment]
I've made a patch for this. It's basically just a `#if` header and function guard.

I'll push to a PR soon, would you be able to test?

I think, in the future, I would aim to refine this guard, and make it check for `libei` and `X11` 'on-the-fly', for dynamicness.

**Comment by darkblaze69** [comment]
Doesn't work for me

```
$ input-leap
The InputLeap GUI requires the DISPLAY environment variable to be set. Quitting...
```

I have no $DISPLAY in wayland-only.

**Comment by shymega** [comment]
It's interesting. We've not had this reported before, so I think this is a good find. I'm going to push again to that PR, with some debugging logger instances.

Do you have the guard in your local sources?

**Comment by shymega** [comment]
I can't reproduce this. I've just built Input Leap from my PR, and I only get the Wayland warning.

**Comment by darkblaze69** [comment]
To be sure we do the same to reproduce, does it launch in your setup?

`DISPLAY= input-leap`

**Comment by shymega** [comment]
I can now reproduce. I think the `$DISPLAY` check is now redundant, and seeing as the only check is in the GUI project - what's stopping a refactor to instead, check `QT_QPA_PLATFORM`? I experimented with using Qt's environment variable store, but I think the QPA platform check is more sane.

We can simply check a valid QPA platform, and then terminate if none is found.

If we do go that way, I'll close #1794, in favour of the new approach.

cc: @p12tic
