### ISSUE TITLE
4 fingers gestures MacOS not work

### ISSUE THREAD

**Issue by bgbruno** [input-leap/input-leap#1798]
### What happened?

nothing happened

### Version

v2.4.0

### If applicable, where did you install Input Leap from?

https://ports.macports.org/port/input-leap/details/

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

MacOS BigSur 11.7.10

### Any other information

https://github.com/input-leap/input-leap/discussions/1796

**Comment by shymega** [comment]
Closing in favour of #1796, which is a feature request. Please avoid opening feature requests as bugs - especially when there's already a Discussion open!
