### ISSUE TITLE
Incorrect app id matching for .desktop icon in Wayland

### ISSUE THREAD

**Issue by darkblaze69** [input-leap/input-leap#1802]
### What happened?

In Wayland session the app shows generic icon. To correctly display the icon in Wayland session desktop file should provide correct app id. IUUC it should be named like com.github.input-leap.desktop or contain "StartupWMClass=com.github.input-leap" in "Desktop entry". Not sure what's the correct way to make it proper.

Before:

![Screenshot from 2023-12-21 01-34-23](https://github.com/input-leap/input-leap/assets/6976920/5d7a759c-0c59-48d0-b35c-2fa3bda53978)

After:

![Screenshot from 2023-12-21 01-39-35](https://github.com/input-leap/input-leap/assets/6976920/4718b642-c6cd-4e29-ad35-9b43767a1507)

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

3e681454

### If applicable, where did you install Input Leap from?

self built install with patches to allow to run in native Wayland.

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Wayland

### What OS versions are you using?

Arch Linux, GNOME 45

**Comment by shymega** [comment]
I discussed this with the Flatpak team. It should be `io.github.input_leap.InputLeap`.
