### ISSUE TITLE
input-leap do not work on my machines

### ISSUE THREAD

**Issue by musicfunfan** [input-leap/input-leap#1813]
### What happened?

I use input-leap on my main machine archlinux(hyprland) and my second machine archlinux(i3wm). 
The server and the clients reads connected but i can not move the mouse from on machine to another machine. 

I think this is a Wayland problem... But i do not know much about it... 

Any ideas on this matter ? 

### Version

v2.4.0

### If applicable, where did you install Input Leap from?

I installed via A.U.R. 

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Server use Wayland (hyprland) 
client use X11.

### What OS versions are you using?

I use archlinux so its rolling...

**Comment by shymega** [comment]
You would need `inputleap-inputcapture` and `libportal-inputcapture` from AUR, but Hyprland and other wlroots-based don't support our Wayland implementation - https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/64 - so you're out of luck, I'm afraid.

Closing as this isn't a bug.

**Comment by musicfunfan** [comment]
Ok. Well double mouse and keyboard it is for now. Thank you for your response.

So can i ask on what Wayland compositors input-leap works on... ?

**Comment by prahal** [comment]
I believe only Gnome Shell (I use 45.3). To me the input leap server support requires mutter to depends on libeis)
