### ISSUE TITLE
Copy paste (possibly formatted) English text from X11 Linux to Windows 10 results in kanji

### ISSUE THREAD

**Issue by spacelama** [input-leap/input-leap#1817]
### What happened?

Copy this text complete with HTML link:
```
VMware End of Availability of perpetual licensing and associated products

https://kb.vmware.com/s/article/96168?lang=en_US
```
from https://www.reddit.com/r/homelab/comments/197mjd1/broadcom_killing_esxi_free_edition/ in firefox on linux (the server) to new Teams (electron?) on Windows10 (the client) results in 
```
洼瑥⁡瑨灴攭畱癩∽潣瑮湥⵴祴数•潣瑮湥㵴琢硥⽴瑨汭※档牡敳㵴瑵ⵦ∸㰾㹰䵖慷敲䔠摮漠⁦癁楡慬楢楬祴漠⁦数灲瑥慵⁬楬散獮湩⁧湡⁤獡潳楣瑡摥瀠潲畤瑣㱳瀯ਾ㰊㹰愼栠敲㵦栢瑴獰⼺欯⹢浶慷敲挮浯猯愯瑲捩敬㤯ㄶ㠶氿湡㵧湥啟≓搠瑡ⵡ牨晥甭汲∽瑨灴㩳⼯扫瘮睭牡⹥潣⽭⽳牡楴汣⽥㘹㘱㼸慬杮攽彮单㸢瑨灴㩳⼯扫瘮睭牡⹥潣⽭⽳牡楴汣⽥㘹㘱㼸慬杮攽彮单⼼㹡⼼㹰
```

Somewhat unexpected, if I copy the text from the github textbox I am typing into, so it's just plaintext, then the paste works fine.

### Version

v2.4.0

### If applicable, where did you install Input Leap from?

debian bullseye, pinned to bullseye-backports
barrier v2.4.0

### What OSes are you seeing the problem on? (Check all that apply)

Linux, Windows

### If applicable, are you using Wayland or X11?

X11

### What OS versions are you using?

server: debian oldstable (bullseye) pinned to bullseye-backports
 Linux dirac 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux

: 29118,2; apt-cache policy xorg
xorg:
  Installed: 1:7.7+22
  Candidate: 1:7.7+22
  Version table:
     1:7.7+23 5
          5 http://ftp.au.debian.org/debian testing/main amd64 Packages
          2 http://ftp.au.debian.org/debian unstable/main amd64 Packages
 *** 1:7.7+22 500
        500 http://ftp.au.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
: 29119,3; apt-cache policy barrier
barrier:
  Installed: 2.4.0+dfsg-3~bpo11+1
  Candidate: 2.4.0+dfsg-3~bpo11+1
  Version table:
     2.4.0+dfsg-4 2
          2 http://ftp.au.debian.org/debian unstable/main amd64 Packages
 *** 2.4.0+dfsg-3~bpo11+1 100
        100 http://ftp.au.debian.org/debian bullseye-backports/main amd64 Packages
        100 /var/lib/dpkg/status
     2.3.3+dfsg-1.1 500
        500 http://ftp.au.debian.org/debian bullseye/main amd64 Packages

Client: Windows 10 Enterprise 10.0.19045 Build 19045

**Comment by shymega** [comment]
This is reproduced from Barrier, not Input Leap. Please avoid opening Barrier bugs here, things in the codebase for Input Leap differ. Closing.
