### ISSUE TITLE
Ubuntu 23.10 client connects to MacOS Sonoma server, but pointer disappears at screen's edge

### ISSUE THREAD

**Issue by davidthewatson** [input-leap/input-leap#1821]
### What happened?

I built MacOS and Ubuntu 23.10 Linux input-leap from source yesterday.

On Ubuntu input-leaps --version shows:

        input-leaps 2.4.0-release
        Protocol version 1.6
        Copyright (C) 2021-2023 InputLeap contributors
        Copyright (C) 2018 Debauchee Open Source Group
        Copyright (C) 2012-2016 Symless Ltd.
        Copyright (C) 2008-2014 Nick Bolton
        Copyright (C) 2002-2014 Chris Schoeneman

I have no trouble running the server on MacOS and the client on Ubuntu, and I get the connection dialog, no problem.

However, despite the successful network connection, the pointer remains still when crossing the configured screen edge, though it does disappear from the MacOS side indicating the switch has been triggered.

Further, the pointer remains invisible until I return back across the screen threshold when it picks up where it left off on the MacOS side. 

The only unusual thing to this configuration is that I'm running Sway. Hence, wayland takes X11's place on the Linux box.

I chose input-leap because I thought the wayland config was supported. Can anyone confirm or deny that this configuration works in any form? I'm not attached to Ubuntu and run sway across all of my Linux boxes from arch to fedora.

If it is supported, then a bug report is the right answer. If not, I'll close the bug report. 

Thanks!

### Version

v2.4.0

### Git commit hash (if applicable)

ced4698751f645a554bd6cda892dc0e34695779f

### If applicable, where did you install Input Leap from?

Source

### What OSes are you seeing the problem on? (Check all that apply)

Linux, macOS

### If applicable, are you using Wayland or X11?

Wayland on Ubuntu 23.10 with input-leapc

### What OS versions are you using?

MacOS Sonoma with input-leaps

**Comment by shymega** [comment]
Sway and other `wlroots` compositors have chosen to not support the new protocol Input Leap uses for Wayland support. You will not be able to use Input Leap on Sway/`wlroots`. Sorry.

Closing as wontfix, as there's not much we can do until we look into alternative ways.
