### ISSUE TITLE
ERROR: could not use ssl certificate: /home/USERNAME/.local/share/InputLeap/SSL/InputLeap.pem

### ISSUE THREAD

**Issue by merlinblack** [input-leap/input-leap#1824]
### What happened?

Freshly installed, I'm seeing this in the logs:
```
[2024-01-31T01:16:55] INFO: OpenSSL 3.1.1 30 May 2023
[2024-01-31T01:16:55] ERROR: could not use ssl certificate: /home/USERNAME/.local/share/InputLeap/SSL/InputLeap.pem
[2024-01-31T01:16:55] ERROR: error:80000018:system library::Too many open files
```
This repeats every 500ms or so.

### Version

v2.4.0

### Git commit hash (if applicable)

004a54fb (from the about box)

### If applicable, where did you install Input Leap from?

Fedora 39 repos as at 2024-01-30 via:
```
sudo dnf install input-leap
```

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

X11 - however I want to switch to Wayland, hence trying out input-leap :-)

### What OS versions are you using?

Fedora 39 (GNOME)

### Relevant log output

```shell
[2024-01-31T01:16:55] INFO: OpenSSL 3.1.1 30 May 2023
[2024-01-31T01:16:55] ERROR: could not use ssl certificate: /home/USERNAME/.local/share/InputLeap/SSL/InputLeap.pem
[2024-01-31T01:16:55] ERROR: error:80000018:system library::Too many open files
```

**Comment by shymega** [comment]
That's a very old revision. Can you please try building from latest Git - there's a guide in the wiki.

Also, is the `/home/USERNAME` what you really see?

**Comment by p12tic** [comment]
`[2024-01-31T01:16:55] ERROR: error:80000018:system library::Too many open files` this error means that the user is hitting against system limits. Any other application that would attempt to open a file would present similar symptom.

The solution is to either close some other applications (most likely there's some application that opened way too many files), or to increase the open files limit. The first tutorial I found is this one https://unix.stackexchange.com/questions/428107/how-to-increase-the-maximum-number-of-open-files-on-fedora, there most likely

**Comment by p12tic** [comment]
I'm closing this bug because the symptoms so far does not indicate that this is a bug in InputLeap.
