### ISSUE TITLE
Label for GUI autostart when Input Leap is ambiguous 

### ISSUE THREAD

**Issue by adam4235** [input-leap/input-leap#1826]
### What happened?

I reported this issue in barrier here: https://github.com/debauchee/barrier/issues/1859

I installed Input Leap on Linux (Pop OS).  Previously I had noticed the issue in barrier when running the server on Linux Mint XFCE edition 21. I check the checkbox "Start Input Leap on startup" (actually it's checked by default), which I'm expecting means the server will start automatically when I reboot my computer. But it didn't (verified by checking the log file). I had to manually add it to the Startup Applications.

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

39e8549cce9711aff7cf177f6feccf4650bff3e7

### If applicable, where did you install Input Leap from?

From source (the git repository)

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

X11

### What OS versions are you using?

Pop!_OS 22.04 LTS

**Comment by prahal** [comment]
The "Start InputLeap on startup" does not enable autostart by the session manager (ie XDG desktop file autostart).
It means starting InputLeap GUI when the input leap daemon (client or server) is started.
It should probably be specified in the setting label, ie "Start InputLeap UI on InputLeap startup".
See commit 297de775a30791682ef5e0993481add3ee38f4b3 "gui: Add autoStart setting" and its doc fragment "Implemented a configuration option for Server GUI auto-start."


I admit it took me a while to sort this out because I assumed as you did that it meant to add input leap to the XDG autostart directory.
As far as I know, there is no way to add InputLeap to session XDG autostart from the input leap code. You have to use a dedicated tool (like gnome-tweaks).

You might want to retitle the bug to "fix confusing setting label for GUI autostart when input leap server starts".

**Comment by shymega** [comment]
The title now sounds like a PR. It's not a good choice of name.

**Comment by sithlord48** [comment]
I agree that this doesn't really describe what the option does,  we really want to convey to the user:

This is how you get a system tray icon if your run input-leapc or input-leaps from outside the gui app. 

What should it say ? 
`Start InputLeap UI with InputLeap's server or  client`
`Show tray icon when inputleap's server or client is running`
`Inputleap UI will start up with the server / client` 

Any other suggestions ?

**Comment by adam4235** [comment]
I guess "Show tray icon when Input Leap is running"?

However, now that I understand that's what the setting does, I'd argue that perhaps it should just be removed?  I'm not sure why someone wouldn't want a tray icon to let them interact with Input Leap.  The tray is supposed to be for background or support applications, to give you a way to access them.  I can understand why they wouldn't want the whole program to start when they turn on their computer (which is what I originally thought the setting was for), but given that they want it to run, why would they want to disable the means of interacting with it?  I believe there's already one program that starts the background server, and another which opens the GUI with the dialog, right?  If they don't want a UI, can't they just run the background server/client?

**Comment by shymega** [comment]
I've changed the title to resemble more of a bug/feature request. The previous two titles were imperative, and from a glance, looked like PRs. Let's avoid that.

I'm keeping this open, as most background apps (particularly on Windows) do, in my experience, offer an option for a tray icon to be suppressed. This behaviour should be kept.

I want to get @p12tic's opinion, though.

cc: @p12tic.

**Comment by sithlord48** [comment]
So what should the label say ?

**Comment by shymega** [comment]
I don't have any preference. I was just passing by to correct the bug title.

**Comment by sithlord48** [comment]
`Show Tray Icon` is short and seams to describe what this does.

**Comment by adam4235** [comment]
@sithlord48 Changing it to "Show Tray Icon" is fine with me, but it looks like your pull request changes it to "Show Tray Icon on startup".  Although that's an improvement I think it might still cause the same confusion from people thinking it means "on computer startup".  In my opinion the "on startup" phrase should be removed.

**Comment by shymega** [comment]
I would change it to "Show Tray Icon upon App Start".
