### ISSUE TITLE
Update Wiki macOS build instruction to include cmake

### ISSUE THREAD

**Issue by kaovilai** [input-leap/input-leap#1832]
### What happened?

Current wiki brew install is not sufficient.
```
brew install qt5 openssl pkg-config
```

I had to also do
```
brew install cmake
```

### Version

From Git HEAD or commit (specify below)

### If applicable, where did you install Input Leap from?

git

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

Sonoma 14.2.1

**Comment by shymega** [comment]
This belongs [here](https://github.com/input-leap/wiki-prs), and isn't an Input Leap codebase bug. Please refrain from opening wiki issues in this tracker.

Even better would be a PR to the linked repository.

Closing.

**Comment by kaovilai** [comment]
There's no link from <codebase/wiki>/README.md to the wiki repo. Also didn't know wiki can be syced from repo.. that's cool.
