### ISSUE TITLE
restarting input leap asks for portal authorization each time

### ISSUE THREAD

**Issue by prahal** [input-leap/input-leap#1843]
### What happened?

When I press reload in input leap server UI I get the authorization popup for the InputCapture each time.
When I press reload in input leap client I get the authorization popup for the RemoteDesktop each time.

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

904dfa31bd1f7d05112b652139eff724e351b8a7

### If applicable, where did you install Input Leap from?

self-built

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Wayland

### What OS versions are you using?

Debian trixie (testing)

### Any other information

I expect to be asked only the first time (with potentially the ability to revoke the access), like an admin policy.
Or at least only be asked once per session or for a time range.

**Comment by shymega** [comment]
Duplicate bug, closing.

**Comment by prahal** [comment]
@shymega can you point me to the duplicate bug for the portal authorization not persisting after an input leap reload?

**Comment by shymega** [comment]
I got mixed up with the screen-saving issue. I will re-open this issue. Apologies for any confusion.

**Comment by prahal** [comment]
@whot would it be possible to not have to interactively allow InputCapture on input-leap server and RemoteDesktop on input-leap client via xdg-portal GUI at all? Or at least persist the setting in some way?

I mean libportal does not ask if we want to authorize access to the filesystem each time we open the file selector.
Could the authorization to access InputCapture and RemoteDesktop behave likewise at least when the request is on the same host?

Maybe this should be moved to libportal issue tracker...

**Comment by whot** [comment]
@prahal: libportal is just a C/GObject wrapper around the DBus communication, the project you're looking for is xdg-desktop-portal which has a permissions store for exactly that. It would have to be integrated into the the two interfaces but there's no technical reason it cannot work.
