### ISSUE TITLE
Cursor disapearing and input not going anywhere after moving offscreen.

### ISSUE THREAD

**Issue by hunterzero99** [input-leap/input-leap#1871]
### What happened?

Starting with commit [650ce407d974baf856b9a1a1298c3c6252b33e93](https://github.com/input-leap/input-leap/commit/650ce407d974baf856b9a1a1298c3c6252b33e93) when I attempt to move my cursor to my client screen it  disappears.  At that point all input is lost and can not be regained.  I have to ssh into my server and kill the input-leaps service to get my input back.

GNOME Linux server (libei) > Windows 10 client

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

650ce407d974baf856b9a1a1298c3c6252b33e93

### If applicable, where did you install Input Leap from?

self-built

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Wayland

### What OS versions are you using?

Arch Linux server & Windows 10 client

**Comment by sithlord48** [comment]
Can you please add to your report the version of libei and libportal  your using as well as if your using Qt5 or Qt6.

**Comment by sithlord48** [comment]
` [2024-02-26T09:17:32] DEBUG1: PlatformScreen::getShape() => x=0 y=0 width=0 height=0` 
Can you try using the the PR `https://github.com/input-leap/input-leap/pull/1866` , this may fix your issue.

**Comment by hunterzero99** [comment]
I built with PR #1866 from the latest commit a20e21f but unfortunately the same issue is still there.

**Comment by darkblaze69** [comment]
I have the same issue since 650ce40. Only able to recover by ssh and `pkill input-leap`.

Connecting to ubuntu 23.10, X11 with barrier 2.4.0+dfsg-4
from Arch, GNOME, Wayland, input-leap from main + libportal 0.7.1+r11 (f15ea50)

**Comment by shymega** [comment]
Bear in mind you won't always be able to mix Barrier and Input Leap.

**Comment by sithlord48** [comment]
@darkblaze69 @hunterzero99  , Can you try the PR that was proposed as a fix ? #1878 please report if it works on the PR. Thanks :smile:

**Comment by hunterzero99** [comment]
This seems to have worked, I built from the following to get all the proposed changes:

` git cherry-pick -n 8ec2059be04c333d8980495a6561106653e5697f da987f70c85e9ba4582658f755e98b749d30a6a0 2b6363ec9f2354e60d596efa04881dd1c41ced1c 7479fbc39583e000d41891324bfa90e687b51641`

**Comment by prurigro** [comment]
The above PR fixes the same issue when the client is running with libei and the server is on X11
