### ISSUE TITLE
Gnome wayland server sometimes starts sending keys as though modifier key is being held down with them

### ISSUE THREAD

**Issue by prurigro** [input-leap/input-leap#1897]
### What happened?

Occasionally after moving from a gnome wayland server to a gnome wayland client, keys will start acting as though I'm holding a modifier down with them. Unlike the previous "sticky modifier" issue where the modifier would need to be triggered by pressing it down, in this case the modifier appears to stuck as the client is entered, and moving it back to the server doesn't reset its state.

I've attempted to strip out irrelevant SSL connection data, and I started the log hopefully after the issue would have been triggered.

[input-leaps.log](https://github.com/input-leap/input-leap/files/14937208/input-leaps.log)

EDIT: I should add that to end this I need to restart the server

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

ga1864cba

### If applicable, where did you install Input Leap from?

Source

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Gnome + wayland

### What OS versions are you using?

Archlinux (latest)

### Any other information

Thanks!

**Comment by prurigro** [comment]
It's possible this is connected to or the same issue as https://github.com/input-leap/input-leap/issues/1690 though I only started noticing it after switching to wayland

**Comment by yuhldr** [comment]
me too
