### ISSUE TITLE
Windows: Unable to use without having Barrier installed.

### ISSUE THREAD

**Issue by JustSxm** [input-leap/input-leap#1898]
### What happened?

After seeing that I had difficulty making Barrier work, I decided to install Input Leap from the debug artifcat and tried it out. After trying it out it worked, so Ive uninstalled Barrier and noticed that Input Leap was just unable to start (Stop at "Starting.." on the server) I restarted my computer to make sure it was not a case of "Windows being Windows", but it still didnt work. I reinstalled barrier and input-leap started working right away.

### Version

v2.4.0

### If applicable, where did you install Input Leap from?

Artifact Github, latest build commit in master
https://github.com/input-leap/input-leap/actions/runs/8426113177/job/23073719166 Qt6

### What OSes are you seeing the problem on? (Check all that apply)

Windows

### What OS versions are you using?

Windows 10

### Any other information

I'd like to know if supporting Windows (with a release) is still in the plans of input-leap

**Comment by dyskette** [comment]
OMG sameee!!! I uninstalled Barrier and input-leap stopped working 😝 

Looking at the logs I saw a message about connection refused:

```
[2024-06-16T09:00:27] INFO: log level: INFO
[2024-06-16T09:00:31] ERROR: ipc connection error, connection refused
[2024-06-16T09:00:32] INFO: connecting to service...
```

I found another issue where it's explained that it's because barrier's service is not running.

https://github.com/input-leap/input-leap/issues/235

The service is not included in the build from github actions either, and I guess it still would need a change somewhere so that it doesn't try to connect to the barrier service and instead try to connect to an input-leap service.

**Comment by pwnednetwork** [comment]
I'm looking at it. (Windows 10/Gentoo/Debian/Kali).

**Comment by x-agent314** [comment]
I noticed this too. I'm gonna look into it although I think I had difficulties building input-leap on Windows last time I remember.
(Windows 10/Gentoo/Debian/Kali)

**Comment by esteves67** [comment]
Same, my input-leap was stuck on "is starting" on both server and client sides, soon as i installed barrier, it worked on both sides, thanks for the help guys

**Comment by SerJoG** [comment]
This is still an issue. On Windows 11 I had also to install Barrier and all works fine. Without Barrier I had "ERROR: ipc connection error, connection refused". All Oses are up to date and both Barrier and InputLeap are the latest version at the date I'm writing this. I also tried making application and port rules on Kaspersky but it doesn't change. Only installing Barrier make it works.
