### ISSUE TITLE
Build issue with: error: ‘xdp_portal_create_remote_desktop_session_full’ was not declared in this scope

### ISSUE THREAD

**Issue by erenfro** [input-leap/input-leap#1912]
### What happened?

With build options in build_env.sh:
`B_CMAKE_FLAGS="-DINPUTLEAP_BUILD_LIBEI=ON -DCMAKE_INSTALL_PREFIX=/opt"`

I get this build error resulting from attempted building:
input-leap/src/lib/platform/PortalRemoteDesktop.cpp:164:5: error: ‘xdp_portal_create_remote_desktop_session_full’ was not declared in this scope; did you mean ‘xdp_portal_create_remote_desktop_session_finish’?

(Full error provided bellow)

### Version

From Git HEAD or commit (specify below)

### If applicable, where did you install Input Leap from?

Compiling from source, current HEAD.

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

N/A

### What OS versions are you using?

openSUSE Tumbleweed 20240607

### Relevant log output

```shell
[ 66%] Building CXX object src/lib/platform/CMakeFiles/platform.dir/EiScreen.cpp.o
[ 66%] Building CXX object src/lib/platform/CMakeFiles/platform.dir/PortalInputCapture.cpp.o
[ 67%] Building CXX object src/lib/platform/CMakeFiles/platform.dir/PortalRemoteDesktop.cpp.o
[ 67%] Linking CXX executable ../../bin/guiunittests
/home/psi-jack/src/other/input-leap/src/lib/platform/PortalRemoteDesktop.cpp: In member function ‘gboolean inputleap::PortalRemoteDesktop::init_remote_desktop_session()’:
/home/psi-jack/src/other/input-leap/src/lib/platform/PortalRemoteDesktop.cpp:164:5: error: ‘xdp_portal_create_remote_desktop_session_full’ was not declared in this scope; did you mean ‘xdp_portal_create_remote_desktop_session_finish’?
  164 |     xdp_portal_create_remote_desktop_session_full(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     xdp_portal_create_remote_desktop_session_finish
gmake[2]: *** [src/lib/platform/CMakeFiles/platform.dir/build.make:370: src/lib/platform/CMakeFiles/platform.dir/PortalRemoteDesktop.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
[ 67%] Built target guiunittests
[ 67%] Linking CXX executable ../../bin/input-leap
gmake[1]: *** [CMakeFiles/Makefile2:669: src/lib/platform/CMakeFiles/platform.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 84%] Built target input-leap
gmake: *** [Makefile:166: all] Error 2
```

**Comment by shymega** [comment]
I get this error too. I think it's a change on a dependency.

**Comment by bryankruman** [comment]
Hey all, I'm getting this issue as well.  Any suggestions on resolution?

**Comment by whot** [comment]
libportal hasn't had a release since that API was added, unfortunately you need to run either a patched version or from git. Having said that, I thought we'd check for that function in cmake somewhere and ifdef things out?

**Comment by shymega** [comment]
Looks like that source file was last edited on Oct 9 2023 by @whot. I wonder if we've just been 'lucky' with builds since then, and it's only just appeared?
