### ISSUE TITLE
Clipboard Sharing not Working in Wayland

### ISSUE THREAD

**Issue by benmordecai** [input-leap/input-leap#1922]
### What happened?

Client and server maintain independent clipboards regardless of which side copies or pastes. This only occurs on Wayland. X11 works fine. 

### Version

v2.4.0

### If applicable, where did you install Input Leap from?

AUR input-leap-inputpacture

### What OSes are you seeing the problem on? (Check all that apply)

Linux, Windows

### If applicable, are you using Wayland or X11?

Wayland

### What OS versions are you using?

Arch linux up to date
Windows 11

**Comment by shymega** [comment]
Dupe of #1698.
