### ISSUE TITLE
Plasma 6.1 - global shortcuts affect server

### ISSUE THREAD

**Issue by PingusPepan** [input-leap/input-leap#1925]
### What happened?

I'm having an issue since upgrading my server computer to Plasma 6.1 (tested 6.1.0, 6.1.1, 6.1.2, 6.1.3)
Client is on Plasma 5.27 but the issue only started after server upgrade (still happens on client with Plasma 6.1.3)

Whenever I press a global shortcut (Printscreen, Ctrl+F1 to switch desktops, Ctrl+Esc which I have set for process monitor, etc.) it runs on both client and server simultaneously. This only happened before with the Super key which was manageable, but the situation right now is really not ideal

Both the server and client run on X11 and I'm using latest input-leap from git compiled locally

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

ef7585e78b7403735bcaa7abd8179f17f3097dc7

### If applicable, where did you install Input Leap from?

self-built

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

X11

### What OS versions are you using?

openSuse 15.6 - server
openSuse 15.6 - client

**Comment by Nicknakin** [comment]
I am also experiencing this issue
X11
Plasma 6.1 
Arch 
Input-Leap v2.4.0-release-release-a1864cba

**Comment by PingusPepan** [comment]
Still present on Plasma 6.1.1

**Comment by shymega** [comment]
Yes, okay. Noted. Let's keep 'me too' comments to a minimum.

**Comment by sithlord48** [comment]
This seams to be a plasma bug . It does not do this on wayland. I suspect its related to the way hotkeys were changed to support single key global hotkeys.

**Comment by fanzhuyifan** [comment]
Hi, the plasma bug should be fixed for ordinary shortcuts (not modifier-only) by https://invent.kde.org/plasma/kglobalacceld/-/commit/d6160f565087979cd07db005536777f3f76b4da6. Could anyone confirm if this does indeed fix the regression, or if the regression still exists with this patch? Thanks!

(To avoid conflicts, you might also need to grab https://invent.kde.org/plasma/kglobalacceld/-/commit/7a6840180e5b710afa59fc297aabddf727173627)

Thanks!

**Comment by PingusPepan** [comment]
Alright, seems fixed by installing Plasma 6.2 on server. So not an issue with InputLeap and I'm closing this issue

Thanks to everyone for providing helpful info and the Plasma team for providing a fix!
