### ISSUE TITLE
Won't switch screens at screen edge

### ISSUE THREAD

**Issue by peterscottie** [input-leap/input-leap#1930]
### What happened?

I can see that the client connects, but nothing happens when i move the mouse to the edge of the screen. This must be a configuration error, but i am really confused.

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

aaeb4829

### If applicable, where did you install Input Leap from?

I built it myself , as the fedora 40 version complained about libportal missing (from memory).

### What OSes are you seeing the problem on? (Check all that apply)

Linux, Windows

### If applicable, are you using Wayland or X11?

This is Wayland on the server and Windows 11 on the client

### What OS versions are you using?

Fedora 40 (server)
Windows 11 (Client)

### Relevant log output

```shell
Sever Log:
      /home/peter/input-leap/src/lib/net/SecureSocket.cpp,857
[2024-06-30T13:19:50] NOTE: accepted client connection
       /home/peter/input-leap/src/lib/server/ClientListener.cpp,138
[2024-06-30T13:19:50] DEBUG1: saying hello
       /home/peter/input-leap/src/lib/server/ClientProxyUnknown.cpp,49
[2024-06-30T13:19:50] DEBUG1: parsing hello reply
       /home/peter/input-leap/src/lib/server/ClientProxyUnknown.cpp,147
[2024-06-30T13:19:50] DEBUG1: querying client "E-CND1487W6S" info
       /home/peter/input-leap/src/lib/server/ClientConnectionLoggingWrapper.cpp,47
[2024-06-30T13:19:50] DEBUG1: created proxy for client "E-CND1487W6S" version 1.6
       /home/peter/input-leap/src/lib/server/ClientProxyUnknown.cpp,199
[2024-06-30T13:19:50] DEBUG: received client "E-CND1487W6S" info shape=0,-1600 5674x2680 at -13108,-13108
       /home/peter/input-leap/src/lib/server/ClientProxy1_6.cpp,430
[2024-06-30T13:19:50] DEBUG1: send info ack to "E-CND1487W6S"
       /home/peter/input-leap/src/lib/server/ClientConnectionLoggingWrapper.cpp,147
[2024-06-30T13:19:50] NOTE: client "E-CND1487W6S" has connected
       /home/peter/input-leap/src/lib/server/Server.cpp,291
[2024-06-30T13:19:50] DEBUG1: send reset options to "E-CND1487W6S"
       /home/peter/input-leap/src/lib/server/ClientConnectionLoggingWrapper.cpp,135
[2024-06-30T13:19:50] DEBUG1: send set options to "E-CND1487W6S" size=24
       /home/peter/input-leap/src/lib/server/ClientConnectionLoggingWrapper.cpp,141
```

### Any other information

[barrier_conf.txt](https://github.com/user-attachments/files/16044203/barrier_conf.txt)

**Comment by peterscottie** [comment]
When i enabled Debug2 I get this repeating in the log file..
2024-06-30T14:22:22] DEBUG2: msg from "E-CND1487W6S": CALV
        /home/peter/input-leap/src/lib/server/ClientProxy1_6.cpp,172
[2024-06-30T14:22:22] DEBUG2: msg from "E-CND1487W6S": CNOP
        /home/peter/input-leap/src/lib/server/ClientProxy1_6.cpp,172
[2024-06-30T14:22:22] DEBUG2: no-op from E-CND1487W6S
        /home/peter/input-leap/src/lib/server/ClientProxy1_6.cpp,237
[2024-06-30T14:22:25] DEBUG2: writing secure socket:0x159ba590
        /home/peter/input-leap/src/lib/net/SecureSocket.cpp,283
[2024-06-30T14:22:25] DEBUG2: reading secure socket
        /home/peter/input-leap/src/lib/net/SecureSocket.cpp,257
[2024-06-30T14:22:25] DEBUG2: reading secure socket
        /home/peter/input-leap/src/lib/net/SecureSocket.cpp,257
[2024-06-30T14:22:25] DEBUG2: want to read, error=2, attempt=1
        /home/peter/input-leap/src/lib/net/SecureSocket.cpp,562
[2024-06-30T14:22:25] DEBUG2: msg from "E-CND1487W6S": CALV
        /home/peter/input-leap/src/lib/server/ClientProxy1_6.cpp,172
[2024-06-30T14:22:25] DEBUG2: msg from "E-CND1487W6S": CNOP
        /home/peter/input-leap/src/lib/server/ClientProxy1_6.cpp,172
[2024-06-30T14:22:25] DEBUG2: no-op from E-CND1487W6S
        /home/peter/input-leap/src/lib/server/ClientProxy1_6.cpp,237
[2024-06-30T14:22:28] DEBUG2: writing secure socket:0x159ba590

**Comment by shymega** [comment]
Wayland is just a set of protocols. We need to know the compositor you are using. I.e,: KDE, GNOME. Sway or other WMs/DEs are *not* supported.

**Comment by peterscottie** [comment]
Ive tried both KDE , and Gnome.. same behavour

**Comment by shymega** [comment]
Have you tried disabling SSL?

**Comment by shymega** [comment]
I would also point to #1898 - possibly a repetition of that bug.

**Comment by shymega** [comment]
Actually, why didn't you use the Fedora COPR? Building Input Leap yourself, without experience, can lead to common pitfalls.

I think you may be missing the correct CMake flag.

**Comment by peterscottie** [comment]
Hi There,
Made a fresh install of fedora , then installed the copr version. which works. I then built the same version from code and it also works.

My feeling is the COPR version installed updated version of some support libararys (i dont remember what it was ) Its now working , but needs crypto disabled.

**Comment by shymega** [comment]
You shouldn't need to disable SSL, but okay. Closing as resolved.

**Comment by JustCryen** [comment]
I have the same issue on Arch. Disabling SSL did not help.  
I have tried lan-mouse and it seems to work fine but requires manual setup on each reboot. (very useful when one of the systems is not supposed to have a keyboard)

**Comment by peterscottie** [comment]
Hi
Heres the command line that i start the server with ..
/usr/bin/input-leaps --use-ei -f --no-tray --disable-crypto --name fedora
--log /var/log/input-leap.log --disable-client-cert-checking -c
./inputleap.conf

Note the --use-ei
As I said before when i added copr repo a couple of libraries were updated
,,

Sorry i cant help more.
/Peter

**Comment by JustCryen** [comment]
Thanks, I will report back if I figure out exactly what's missing

**Comment by JustCryen** [comment]
I just noticed that reversing the client / server between these two computers made it work for me.
The one that was supposed to be server is running Wayland and the other is X11. It's not working in this configuration but it is fine the other way around, even with crypto / SSL and certificate checking.
So I guess having a server running from Wayland is still an issue.
