### ISSUE TITLE
Moving Mouse to Another Device Causes Taskbar to Overlay Fullscreen Application

### ISSUE THREAD

**Issue by markg85** [input-leap/input-leap#1931]
### What happened?

Copy of https://github.com/debauchee/barrier/issues/1933 as that very issue is still there.

My setup is my external "pc" is on the left of the pc i'm running the input-leap server on.
I'm running a fullscreen app (the "other pc") but as soon as i move my mouse to the left to access that app then the taskbar of my host shows up.

I cannot find the config to disable that.

### Version

From Git HEAD or commit (specify below)

### If applicable, where did you install Input Leap from?

Archlinux from the AUR repository

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

X11

### What OS versions are you using?

Arch

**Comment by shymega** [comment]
You need to test with Input Leap. Barrier and Input Leap have diverged.

Please test.

**Comment by markg85** [comment]
Your taskbar overlaps the fullscreen window.

It's a bit hard to make screenshots of so i prefer following steps.

So, try this on Linux (i'm trying it on Arch Linux with Plasma as desktop):
1. Have input-leap setup so that moving to the LEFT is your external thing you want to monitor. You **must** have a connection in input-leap to a client! And you **must** be trying these commands on the "server" side (the pc with the keyboard and mouse).
2. Start an mpv window as fullscreen, no video needed. `mpv --input-cursor=no --input-vo-keyboard=no --fullscreen --player-operation-mode=pseudo-gui` note that you explicitly have no cursor and no keyboard input. You can quit with ALT + F4.
3. Your screen should now be filled with mpv. **No** taskbar should be visible.
4. Move your cursor to the left to the pc you're controlling.
5. Observe that the taskbar shows up as long as your cursor is in the area of the screen you're controlling

I hope this works as making screenshots or even a video isn't going to show this properly. I'd have to film it otherwise... ugh.

**Comment by markg85** [comment]
That works!

Any reason why that isn't the default?

**Comment by shymega** [comment]
Because setting defaults could be detrimental to most users. If this happens to other users, it might be worth setting it as default. But currently not. Closing as resolved.
