### ISSUE TITLE
CI Rpms are not built to use LIBEI

### ISSUE THREAD

**Issue by sithlord48** [input-leap/input-leap#1948]
### What happened?

Our rpm spec files needs to be updated to have  libei and what ever portal stuff as a dependency as well as be configured to use it. This is why the rpm is falling back to xwayland.

### Version

From Git HEAD or commit (specify below)

### If applicable, where did you install Input Leap from?

CI built RPM Files.

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Wayland ONLY 

### What OS versions are you using?

Fedora / Suse , Other RPM based distros using our CI package

**Comment by KoljaFrahm** [comment]
For Fedora 40 with Gnome 46, my package names are:
libei.x86_64
libei-devel.x86_64
libportal.x86_64
libportal-gtk3.x86_64
libportal-gtk4.x86_64
for libei and libportal.

**Comment by whot** [comment]
These days specifying build deps as pkgconfig deps is the best approach:
```
BuildRequires: pkgconfig(libei-1.0)
BuildRequires: pkgconfig(libportal)
```

That will resolve to "package that provides libei-1.0.pc" and "package that provides libportal.pc".

**Comment by whot** [comment]
Oh, and looking at the `input-leap.spec.in` file: you should not need `Requires: libfoo`, that is handled automatically if the library is built in. You should be able to ditch all `Requires` lines afaict.

**Comment by sithlord48** [comment]
If either of you guys can make a PR that you can test please do. I don't use a distro where i can test rpm installs easily.

**Comment by KoljaFrahm** [comment]
I created a PR. But we have to wait until https://src.fedoraproject.org/rpms/libportal/pull-request/5 is merged, with the old libportal version it doesn't work yet.

**Comment by KoljaFrahm** [comment]
Also for suse I changed everything to the best of my knowledge but I can't test it

**Comment by KoljaFrahm** [comment]
Fixed with https://github.com/input-leap/input-leap/pull/1954 and can be closed
