### ISSUE TITLE
Error compiling on macOS git from master

### ISSUE THREAD

**Issue by t00** [input-leap/input-leap#1950]
### What happened?

I have been trying to follow the compilation steps on macOS. It seems the wiki page is outdated compared to current codebase and mentions qt5 which does not seem to match the dependencies of the input-leap project.

After amending brew installation to be:

```brew install qt5 openssl pkg-config cmake```

and running

```./clean_build.sh```

There are several errors on 37% progress compiling unit tests (shortened for brevity)

Qt6 version: 6.7.0_1

Is there anything I can help with to make the build work?

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

3a95e113435c6433d2f718ee55a4f688ec1ff893

### If applicable, where did you install Input Leap from?

git

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

14.6 (23G80)

### Relevant log output

```shell
[ 37%] Building CXX object src/gui/CMakeFiles/guiunittests.dir/src/KeySequence.cpp.o
In file included from /Users/mt/dev/temp/input-leap/src/gui/test/KeySequenceTests.cpp:18:
In file included from /Users/mt/dev/temp/input-leap/src/gui/test/Utils.h:19:
In file included from /opt/homebrew/include/QtCore/QFile:1:
/opt/homebrew/lib/QtCore.framework/Headers/qfile.h:59:58: error: 'path' is unavailable: introduced in macOS 10.15
inline QString fromFilesystemPath(const std::filesystem::path &path)
                                                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__filesystem/path.h:446:33: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_EXPORTED_FROM_ABI path {
                                ^
In file included from /Users/mt/dev/temp/input-leap/src/gui/test/KeySequenceTests.cpp:18:
In file included from /Users/mt/dev/temp/input-leap/src/gui/test/Utils.h:19:
In file included from /opt/homebrew/include/QtCore/QFile:1:
/opt/homebrew/lib/QtCore.framework/Headers/qfile.h:64:40: error: 'native' is unavailable: introduced in macOS 10.15
    return QString::fromStdString(path.native());
                                       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__filesystem/path.h:779:22: note: 'native' has been explicitly marked unavailable here
  const string_type& native() const noexcept { return __pn_; }
                     ^
In file included from /Users/mt/dev/temp/input-leap/src/gui/test/KeySequenceTests.cpp:18:
In file included from /Users/mt/dev/temp/input-leap/src/gui/test/Utils.h:19:
In file included from /opt/homebrew/include/QtCore/QFile:1:
/opt/homebrew/lib/QtCore.framework/Headers/qfile.h:68:25: error: 'path' is unavailable: introduced in macOS 10.15
inline std::filesystem::path toFilesystemPath(const QString &path)
                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__filesystem/path.h:446:33: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_EXPORTED_FROM_ABI path {
                                ^
In file included from /Users/mt/dev/temp/input-leap/src/gui/test/KeySequenceTests.cpp:18:
In file included from /Users/mt/dev/temp/input-leap/src/gui/test/Utils.h:19:
In file included from /opt/homebrew/include/QtCore/QFile:1:
/opt/homebrew/lib/QtCore.framework/Headers/qfile.h:70:29: error: 'path' is unavailable: introduced in macOS 10.15
    return std::filesystem::path(reinterpret_cast<const char16_t *>(path.cbegin()),
                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__filesystem/path.h:446:33: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_EXPORTED_FROM_ABI path {
                                ^
In file included from /Users/mt/dev/temp/input-leap/src/gui/test/KeySequenceTests.cpp:18:
In file included from /Users/mt/dev/temp/input-leap/src/gui/test/Utils.h:19:
In file included from /opt/homebrew/include/QtCore/QFile:1:
/opt/homebrew/lib/QtCore.framework/Headers/qfile.h:70:12: error: 'path<const char16_t *>' is unavailable: introduced in macOS 10.15
    return std::filesystem::path(reinterpret_cast<const char16_t *>(path.cbegin()),
           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__filesystem/path.h:492:3: note: 'path<const char16_t *>' has been explicitly marked unavailable here
  path(_InputIt __first, _InputIt __last, format = format::auto_format) {
  ^
In file included from /Users/mt/dev/temp/input-leap/src/gui/test/KeySequenceTests.cpp:18:
In file included from /Users/mt/dev/temp/input-leap/src/gui/test/Utils.h:19:
In file included from /opt/homebrew/include/QtCore/QFile:1:
/opt/homebrew/lib/QtCore.framework/Headers/qfile.h:70:12: error: 'path' is unavailable: introduced in macOS 10.15
    return std::filesystem::path(reinterpret_cast<const char16_t *>(path.cbegin()),

...


fatal error: too many errors emitted, stopping now [-ferror-limit=]
16 errors generated.
16 errors generated.
make[2]: *** [src/gui/CMakeFiles/guiunittests.dir/test/HotkeyTests.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/gui/CMakeFiles/guiunittests.dir/test/KeySequenceTests.cpp.o] Error 1
20 errors generated.
make[2]: *** [src/gui/CMakeFiles/guiunittests.dir/src/KeySequence.cpp.o] Error 1
make[1]: *** [src/gui/CMakeFiles/guiunittests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 37%] Linking CXX static library libsynlib.a
[ 37%] Built target synlib
[ 37%] Built target input-leap_autogen
make: *** [all] Error 2
```

**Comment by smcdonald45** [comment]
Any news here? I have the same problem.

**Comment by shymega** [comment]
Hi,

Please avoid bumping the issue when unnecessary.

If you also experience the issue, kindly react to the issue with `:+1:`, or if you want to find out when the issue will be resolved, please do not bump the issue, but _instead_ subscribe to the issue using the button on the right-hand side.

**Comment by FightingSu** [comment]
Hi, I encountered the same problem. This problem can be fixed by modifying `clean_build.sh`.

You should change line 21 from this

```bash
B_CMAKE_FLAGS="${B_CMAKE_FLAGS} -DCMAKE_OSX_SYSROOT=$(xcrun --sdk macosx --show-sdk-path) -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9"
``` 

to

```bash
B_CMAKE_FLAGS="${B_CMAKE_FLAGS} -DCMAKE_OSX_SYSROOT=$(xcrun --sdk macosx --show-sdk-path) -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15"
```

It seems that some libraries are introduced since macOS 10.15. By updating macro `CMAKE_OSX_DEPLOYMENT_TARGET`, these libraries are enabled.

**Comment by mikehardy** [comment]
@FightingSu the error in the compile indicates it requires 10.15+ and your fix works perfectly, I proposed #1977 with that change. Cheers

**Comment by sithlord48** [comment]
The clean build script is not maintained. or used anywhere

**Comment by nbolton** [comment]
> The clean build script is not maintained. or used anywhere

Damn. Sounds like dead code.

**Comment by eljobe** [comment]
If it isn't maintained or used anywhere, then it should probably be removed from the Wiki instructions for how to build on MacOS X.
<img width="911" alt="image" src="https://github.com/user-attachments/assets/07b2ea1c-57e3-49ef-b740-a84339e85cea">

And, ideally, replaced with whatever is used and maintained.

You could also consider removing the script from the repo.

**Comment by sithlord48** [comment]
Wiki should say https://github.com/input-leap/input-leap/pull/1977#issuecomment-2380627077

**Comment by KoljaFrahm** [comment]
It also says on Linux to use 
`./clean_build.sh`
Then this should also be replaced.

**Comment by shymega** [comment]
Personally, I think we should keep `clean_build.sh`, but _only_ for quick builds. Users should use packages from distros/Flatpak/Snap/CI, but for quickly iterating in development, the script is useful.

**Comment by sithlord48** [comment]
you would think that but in the long run these scripts make it harder to follow what is going on . 

You wanna make an easy script it gonna need to take options to see the various cmake options so now instead of just documenting what the cmake options are your not also making extra documentation to tell people how to use the scripts.

**Comment by sithlord48** [comment]
> Personally, I think we should keep `clean_build.sh`, but _only_ for quick builds. Users should use packages from distros/Flatpak/Snap/CI, but for quickly iterating in development, the script is useful.

How so ? Anyone developing is using an iDE the scripts are not used there. The configuration could be vastly different then what the build script forces.

**Comment by nbolton** [comment]
> The configuration could be vastly different then what the build script forces.

Assuming by this you mean: the developer's existing config could be different, and you don't want a script to mess with that.

This is a really good point.

**Comment by sithlord48** [comment]
> > The configuration could be vastly different then what the build script forces.
> 
> Assuming by this you mean: the developer's existing config could be different, and you don't want a script to mess with that.
> 
> This is a really good point.

Late on the reply but yes that is exactly what i was trying to say
