### ISSUE TITLE
Release 3.0.1 starting with Xwayland in debian packages

### ISSUE THREAD

**Issue by theofficialgman** [input-leap/input-leap#2009]
### What happened?

Release 3.0.1 is starting with xwayland (for unknown reasons). This issue did not occur on the prior github actions (tarfile) build I was using `2.4.0-release-release-3a95e113`

### Version

v3.0.1

### If applicable, where did you install Input Leap from?

https://github.com/input-leap/input-leap/releases/download/v3.0.1/InputLeap_3.0.1_ubuntu_22-04_amd64.deb

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Wayland

### What OS versions are you using?

Ubuntu Neon 24.04

### Relevant log output

```shell
[2024-10-10T17:41:48] INFO: SSL fingerprint generated.

[2024-10-10T17:41:48] INFO: starting server
[2024-10-10T17:41:48] INFO: config file: /tmp/InputLeap.BwPNQb
[2024-10-10T17:41:48] INFO: log level: INFO
[2024-10-10T17:41:48] WARNING: Running against Xwayland. InputLeap will not work as expected
started server (IPv4/IPv6), waiting for clients
```

**Comment by theofficialgman** [comment]
Bug is simple, libei is not enabled in debian builds https://github.com/input-leap/input-leap/blob/81d7a3cefb0cca90e7a8692dad599724325b6cf4/dist/debian/rules#L24

**Comment by p12tic** [comment]
> Bug is simple, libei is not enabled in debian builds 

This is correct, because on Ubuntu we would need to distribute libportal within the deb package.

I just wanted to get the release out faster and think about this later for the next patch release.

**Comment by theofficialgman** [comment]
Understandable. I will use the flatpak package for now (hopefully this can come to flathub soon)

**Comment by p12tic** [comment]
@theofficialgman Just to double check - is it correct that on your Ubuntu 24.04 only input control works, but not input capture?

**Comment by p12tic** [comment]
@theofficialgman Could you please test this deb package https://github.com/input-leap/input-leap/actions/runs/11299349857 ? It should contain the same build config as previous package from github actions.

**Comment by p12tic** [comment]
Tested https://github.com/input-leap/input-leap/pull/2024 on latest KDE Neon (as of 2024-10-13). Seems to work.

**Comment by p12tic** [comment]
@theofficialgman please reopen the issue if the fix doesn't work for you

**Comment by theofficialgman** [comment]
> Tested #2024 on latest KDE Neon (as of 2024-10-13). Seems to work.

Doesn't work out of the box as libei1 and libportal1 from the distro (still ubuntu 24.04) is used (libei1 1.2.1 and libportal1 0.7.1). I'll let Neon devs know and they should update them to latest versions

**Comment by p12tic** [comment]
Note that we previously didn't distribute libei1 and libportal1, so Input Leap was still using the libraries provided by the distribution.
