### ISSUE TITLE
Cmd/Option key swapping for MacOSX.

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#201]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/201
> 
> Issue created on: 2018-12-17 by @memecode
> Issue last updated on: 2021-11-04

### Operating Systems ###

Server: Windows 10
Client: MacOSX 10.13.4

### Barrier Version ###

2.1.0 on both machines

### Steps to reproduce bug ###

Normally I would use 'Alt' on the windows keyboard as the Command ⌘ key. And apparently you can map it to do that [using the .conf file](https://gist.github.com/wpiekutowski/1259289). By default the windows key maps to command and alt maps to option.

So what I'd like to see is that there is options to map the windows key -> option, and the alt key to command in the user interface. But failing that I need to be able to find the barrier.conf file to edit it directly. Currently it's location is not discoverable by new users. Sure it says "configuration file" in the UI for the server but that file doesn't exist on my mac client... so where is it saving my client specific settings? The man page is not installed and reading the code seems to indicate "~/barrier.conf".

However if I view the log I get this:
[2018-12-18T10:49:18] INFO: starting client
[2018-12-18T10:49:18] INFO: config file: /var/folders/f1/4dbtx98n2mg737sn2y0v3vpw0000gr/T/Barrier.eWezhq
[2018-12-18T10:49:18] INFO: log level: INFO

It seems to be auto-generating new config file paths every time I run it. I've spent far too long trying to edit the config to fix the keys.

### Other info ###

This isn't a show stopper but it's pretty annoying to have to manually adjust to different modifier  keys to use for copy and paste...

---

> Commented on: 2018-12-18 by @AdrianKoshka

Is this what you're looking for? (alc.localdomain is the client)

![2018-12-17-190156_439x437_scrot](https://user-images.githubusercontent.com/8690255/50123335-4a4fb680-022e-11e9-95d7-a3c63d2b9ed2.png)

---

> Commented on: 2018-12-18 by @AdrianKoshka

fwiw, every machine has this UI dialogue: (This is the server)

![2018-12-17-190331_439x437_scrot](https://user-images.githubusercontent.com/8690255/50123401-8420bd00-022e-11e9-9576-4218a928b5c2.png)

can be found by double-clicking any of the machines in the configure server dialogue:

![2018-12-17-190323_795x534_scrot](https://user-images.githubusercontent.com/8690255/50123436-9bf84100-022e-11e9-817a-e17134c6980b.png)

---

> Commented on: 2018-12-18 by @memecode

> 
> 
> Is this what you're looking for? (alc.localdomain is the client)
> 
> ![2018-12-17-190156_439x437_scrot](https://user-images.githubusercontent.com/8690255/50123335-4a4fb680-022e-11e9-95d7-a3c63d2b9ed2.png)

Yes that is what I need. It's just difficult to find because I was expecting it to be on the client side.

The discoverable version of this is a menu option on the client like File->Screen Settings or something that brings up that dialog on the client side (or any side really... just for the local machine, be it client or server). Is that something that would be acceptable to add? Like if I submit a patch what is the likely hood of it being accepted?

---

> Commented on: 2018-12-18 by @memecode

Actually one option would be to merge the "settings" dialog and the "screen settings" dialog so that everything is in one place. The fact that there are 2 different sets of settings isn't obvious to new users. I found the "settings" easily enough but it didn't let me edit the key modifier mappings.

---

> Commented on: 2018-12-18 by @AdrianKoshka

I admit it's not perfect, it's something we inherited from synergy. Did this solve your issue though?

---

> Commented on: 2018-12-18 by @memecode

> I admit it's not perfect, it's something we inherited from synergy. Did this solve your issue though?

Yes I got it working how I want now. This is what I ended up with:
![settings](https://i.imgur.com/KAtdF0c.png)

---

> Commented on: 2020-08-03 by @harshhpareek

@AdrianKoshka I had some trouble finding this. It deserves to be on the main FAQ page.

---

> Commented on: 2020-10-30 by @LaszloGombos

Change will only take affect after stop/start the server (reload config does not seem to be enough).

---

> Commented on: 2021-11-04 by @amanjeev

![image](https://user-images.githubusercontent.com/160476/140401684-17c13dbd-dd3f-42df-98a9-9a7cd95641e7.png)

This is my setup to make this work.  I had to leave super as is and turn off ctrl because scrolling on mac client would end up zooming in and out instead of scrolling.  So the other solutions in this discussion did not work for me. 

server - ubuntu
client - macos
barrier version 2.3.3

---

> Closed on: 2019-01-15 by @AdrianKoshka

**Comment by jakelauer** [comment]
For anyone in a situation like mine where you have an OS X server with a Windows client, I left the configuration for the server machine as-is, and used the following mapping for the Windows client:

| Shift | Shift |
|-------|-------|
| Ctrl  | Super |
| Alt   | Alt   |
| Meta  | Meta  |
| Super | Ctrl  |
