### ISSUE TITLE
Add to winget

### ISSUE THREAD

**Issue by KoljaFrahm** [input-leap/input-leap#2017]
### What happened?

Input-leap 3.0.1 should added to winget (https://github.com/microsoft/winget-pkgs/blob/master/doc/README.md) similar to the barrier manifest (https://github.com/microsoft/winget-pkgs/tree/master/manifests/d/DebaucheeOpenSourceGroup/Barrier/2.4.0)

### Version

v3.0.1

### If applicable, where did you install Input Leap from?

Not winget

### What OSes are you seeing the problem on? (Check all that apply)

Windows

### What OS versions are you using?

Windows

**Comment by KoljaFrahm** [comment]
I created a pull request:
https://github.com/microsoft/winget-pkgs/pull/181384

**Comment by p12tic** [comment]
Thanks @KoljaFrahm for taking case of this issue.

**Comment by KoljaFrahm** [comment]
PR was merged, created one for 3.0.2 too
