### ISSUE TITLE
Using older OS X

### ISSUE THREAD

**Issue by patrikaxelsson** [input-leap/input-leap#2035]
### What happened?

Using Input Leap 3.0.1 under OS X High Sierra 10.13, this machine can't be upgraded.

With the current 3.0.2 support for this machine is dropped.

### Version

v3.0.1

### If applicable, where did you install Input Leap from?

The 3.0.1 release on github

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

High Sierra 10.13

**Comment by p12tic** [comment]
I've also got several emails about this. We'll bring back support for older operating systems, it's not that hard to support.

cc @shymega

**Comment by patrikaxelsson** [comment]
Cheers :)

**Comment by g-l-i-t-c-h-o-r-s-e** [comment]
> I've also got several emails about this. We'll bring back support for older operating systems, it's not that hard to support.
> 
> cc [@shymega](https://github.com/shymega)

any plans on this still? current version 3.0.3 crashes on MacOS High Sierra 10.13.6 :(
