### ISSUE TITLE
[MacOS Sequoia] Stuck at InputLeap is starting when run as Server.

### ISSUE THREAD

**Issue by akshuvo** [input-leap/input-leap#2044]
### What happened?

![image](https://github.com/user-attachments/assets/fa60ab87-3c01-4f53-95df-90e4e0bd3f72)

I cannot start as server from my mac m1.

### Version

v3.0.2

### If applicable, where did you install Input Leap from?

From the release.

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

MacOS Sequoia - Version 15.0.1 (24A348)

### Relevant log output

```shell
[2024-10-16T01:09:33] INFO: starting server
[2024-10-16T01:09:33] INFO: config file: /private/var/folders/7j/xckghshs7k971fffvd5_sl8m0000gn/T/InputLeap.eEXIzo
[2024-10-16T01:09:33] INFO: log level: INFO

[2024-10-16T01:09:33] FATAL: An error occurred: assistive devices does not trust this process, allow it in system settings.
[2024-10-16T01:09:34] ERROR: process exited with error code: 1
[2024-10-16T01:09:34] INFO: detected process not running, auto restarting
```

**Comment by steveDvlpr** [comment]
You have to allow the _Input Leap_ app in your Mac system settings. Open the _Settings_ app, go to _Privacy & Security_ and then to _Accessibility_. Add the app there so it can control your Mac.

**Comment by rabbitmaiden** [comment]
I'm also seeing this from a fresh install of 3.0.4 just now. I have enabled Input Leap in the Accessibility list and it's turned on but trying to start the server still gives the "assistive devices does not trust this process" loop.

![image](https://github.com/user-attachments/assets/61540e07-1ca9-4f2f-99d6-ad1a125944db)

**Comment by rabbitmaiden** [comment]
I was also running into this until I realized I'm on MacOS 14.6.1. I tried going back to 3.0.0 and it still didn't work, so I assume the MacOS 15 is a requirement for all the 3.x builds.

**Comment by akshuvo** [comment]
> You have to allow the _Input Leap_ app in your Mac system settings. Open the _Settings_ app, go to _Privacy & Security_ and then to _Accessibility_. Add the app there so it can control your Mac.

I did but not working. I can use Mac as client but not as server.

**Comment by akshuvo** [comment]
> > You have to allow the _Input Leap_ app in your Mac system settings. Open the _Settings_ app, go to _Privacy & Security_ and then to _Accessibility_. Add the app there so it can control your Mac.
> 
> Got same issue and it's enabled in accessibility
> 
> edit: [#1322 (comment)](https://github.com/input-leap/input-leap/issues/1322#issuecomment-2352294879)
> 
> it's that but with more steps and it works.

This works :)

**Comment by Luda83** [comment]
> > You have to allow the _Input Leap_ app in your Mac system settings. Open the _Settings_ app, go to _Privacy & Security_ and then to _Accessibility_. Add the app there so it can control your Mac.
> 
> Got same issue and it's enabled in accessibility
> 
> edit: [#1322 (comment)](https://github.com/input-leap/input-leap/issues/1322#issuecomment-2352294879)
> 
> it's that but with more steps and it works.

This also worked for me, Thank you!!

**Comment by IbrahimOezhan** [comment]
I cannot personally select the binary within the .app file. Just the .app file. And I gave it both required permissions and its still stuck in starting. Maybe some logs should be added as to what is actually happening
