### ISSUE TITLE
APT installation works, but gives an error message

### ISSUE THREAD

**Issue by ViBE-HU** [input-leap/input-leap#2055]
### What happened?

Tried to install the latest build on Ubuntu 24.04. It gives me a strange output:

```
$ sudo apt install ./InputLeap_3.0.2_ubuntu_24-04_amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'input-leap' instead of './InputLeap_3.0.2_ubuntu_24-04_amd64.deb'
The following NEW packages will be installed:
  input-leap
0 upgraded, 1 newly installed, 0 to remove and 16 not upgraded.
Need to get 0 B/778 kB of archives.
After this operation, 2746 kB of additional disk space will be used.
Get:1 /home/user/Downloads/InputLeap_3.0.2_ubuntu_24-04_amd64.deb input-leap amd64 3.0.2 [778 kB]
Selecting previously unselected package input-leap.
(Reading database ... 276321 files and directories currently installed.)
Preparing to unpack .../InputLeap_3.0.2_ubuntu_24-04_amd64.deb ...
Unpacking input-leap (3.0.2) ...
Setting up input-leap (3.0.2) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for man-db (2.12.0-4build2) ...
N: Download is performed unsandboxed as root as file '/home/user/Downloads/InputLeap_3.0.2_ubuntu_24-04_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
```

### Version

v3.0.2

### If applicable, where did you install Input Leap from?

GitHub release

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

X11

### What OS versions are you using?

Ubuntu 24.04

**Comment by nbolton** [comment]
You mean this?
```
N: Download is performed unsandboxed as root as file '/home/user/Downloads/InputLeap_3.0.2_ubuntu_24-04_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
```

Yeah I always wondered about that. Seems innocuous but probably not something we should ignore.

**Comment by ViBE-HU** [comment]
Yes. I'm a noob but I never seen this kind of message before. I thought it might worth to mention.

**Comment by nbolton** [comment]
> Yes. I'm a noob but I never seen this kind of message before. I thought it might worth to mention.

I'm an apt noob too :smiley: 
I have no idea what it means. Would be nice to see it fixed.

**Comment by scrummyin** [comment]
You might want to try `$ sudo dpkg -i InputLeap_3.0.2_ubuntu_24-04_amd64.deb`, which might result in broken packages but an `$ sudo apt install --fix-missing` afterwards could help solve that.  I haven't had the best experience with apt installing `.deb` packages from the cli, but `dpkg` has always been happy to do it.

**Comment by shymega** [comment]
This is not an Input Leap bug.

**Comment by ViBE-HU** [comment]
> This is not an Input Leap bug.

Understood. But is it a packaging related issue or it is an APT issue in general?

**Comment by shymega** [comment]
I think it's due to local system permissions. I don't think it's a packaging issue.

**Comment by EdgyVini** [comment]
There answers on the web:   https://orcacore.com/fix-apt-error-download-is-performed-unsandboxed-as-root/

I am a nubee too but when I was upgrading to the new version of Zoom I encountered this.  So I Googled it - Tada !!  

Who knew?
