### ISSUE TITLE
Seg fault when attempting to access "Configure Server..." dialog on Arch linux

### ISSUE THREAD

**Issue by acepukas** [input-leap/input-leap#2067]
### What happened?

When clicking the `Configure server...` button in the input-leap GUI, the program crashes. Running input-leap from the terminal and repeating the same steps indicates that the crash is due to a segmentation fault.

### Version

v3.0.2

### If applicable, where did you install Input Leap from?

The Arch linux AUR input-leap package

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Wayland

### What OS versions are you using?

Arch Linux and MacOS Sequoia

### Any other information

I've made sure that all optional dependencies were installed when installing the input-leap package from the AUR in case the crash was due to missing deps but that didn't fix the issue.

**Comment by nPHYN1T3** [comment]
I can second the issue.

**Comment by sithlord48** [comment]
https://github.com/deskflow/deskflow/pull/7753

**Comment by nbolton** [comment]
> I fixed it in deskflow: [deskflow/deskflow#7753](https://github.com/deskflow/deskflow/pull/7753) should apply directly to input leap as well

Good fix. So far Arch Linux and openSUSE both have bumped Qt to the version that causes this warning.

**Comment by SilasMouraDev** [comment]
Hello! Exact same issue on Fedora 41.
Both from Fedora repositories or building from source.
I followed the Wiki [guide](https://github.com/input-leap/input-leap/wiki/Building-on-Linux)
[backtrace.txt](https://github.com/user-attachments/files/17600921/backtrace.txt)

**Comment by sithlord48** [comment]
What version are you running @SilasMouraDev  ?

**Comment by delight** [comment]
Same problem on:
Distributor ID: Neon
Description:    KDE neon 6.2
Release:        24.04
Codename:       noble

with InputLeap Version: 3.0.2-release-release-7e5889dc

**Comment by Scrambler-77** [comment]
Same here: Arch+Gnome/Wayland

**Comment by Jakjm** [comment]
I've created a PR with the changes proposed by sithlord48

**Comment by shymega** [comment]
Thanks @Jakjm - I've just requested a review from @p12tic on this. The PR should be expedited given the nature of the bug.

**Comment by Jakjm** [comment]
Just to note as well, since I didn't before, I reproduced this bug on my own Arch Linux system before implementing the changes. Once the changes were made, the bug is no longer present (I am able to configure the server without a segfault)

**Comment by anh0516** [comment]
I just tried to set up Input Leap between two Fedora 41 machines, and encountered this issue. Both are up to date running version 3.0.2, which should have the fix, but it's still broken.

Here's the report from the Red Hat bugtracker:
https://bugzilla.redhat.com/show_bug.cgi?id=2326185

**Comment by shymega** [comment]
> I just tried to set up Input Leap between two Fedora 41 machines, and encountered this issue. Both are up to date running version 3.0.2, which should have the fix, but it's still broken.
> 
> Here's the report from the Red Hat bugtracker: https://bugzilla.redhat.com/show_bug.cgi?id=2326185

No, v3.0.2 does _not_ have the fix.

**Comment by anh0516** [comment]
> No, v3.0.2 does _not_ have the fix.

Guess I read things wrong, then. A hotfix release wouls be a good idea.

**Comment by shymega** [comment]
I would close the bug on Red Hat as well - as for the hotfix, I don't know when we'll make one.

**Comment by anh0516** [comment]
> I would close the bug on Red Hat as well - as for the hotfix, I don't know when we'll make one.

I can't close that because it's not mine. For now I'll build it myself, not the end of the world.

**Comment by shymega** [comment]
Ah, my apologies. I misread the ticket, which I realised after my post.

You may want to checkout SHA 2641bc502e16b1fb7372b43e94d4b894cbc71279 locally, and build from that.

**Comment by anh0516** [comment]
[0001-fix-qt68.patch.txt](https://github.com/user-attachments/files/18141287/0001-fix-qt68.patch.txt)
I used this patch file to build a working Fedora 41 package with the existing Fedora template. I'm sure there's a way to tell `fedpkg` to checkout a specific commit, but I'm not familiar enough with their packaging system.
