### ISSUE TITLE
MacOS Sequoia - assistive devices does not trust this process

### ISSUE THREAD

**Issue by fredodupoux** [input-leap/input-leap#2075]
### What happened?

At first launch you are asked to allow permissions in Privacy & Security > Accessibility. After quit & reopen app runs, but server can't start and the log shows:
"FATAL: An error occurred: assistive devices does not trust this process, allow it in system settings."

To fix this i had to drag /Applications/InputLeap.app/Contents/MacOS/input-leap into Accessibility's allowed list.
Server now runs and clients connect but Meta key doesn't work, alt key doesn't work, clipboard doesn't work in both directions. 

Went back to using Barrier Server 2.4.0 for everything to work normally again. 

### Version

v3.0.2

### If applicable, where did you install Input Leap from?

Downloaded from the releases.
MacOS as a server
Wayland as a client

### What OSes are you seeing the problem on? (Check all that apply)

Linux, macOS

### If applicable, are you using Wayland or X11?

Wayland as a client

### What OS versions are you using?

MacOS Sequoia Version 15 and 15.1 (24B83)

### Relevant log output

```shell
[2024-10-30T10:56:46] FATAL: An error occurred: assistive devices does not trust this process, allow it in system settings.
```

**Comment by castle-samj** [comment]
I can confirm this behavior, and workaround. Additionally, pointer control is transferred according to logs, but pointer not visible on Windows11 client.

**Comment by dbouwer** [comment]
I have the same issue. The workaround mentioned above does work. No issues on Win11 client.

**Comment by zgastley** [comment]
I had the same issue - I found a similar issue in the Barrier closed items and the solution also worked.

https://github.com/debauchee/barrier/issues/1322

In short, navigate to  `Applications/InputLeap.app/Contents/MacOS/` and drag and drop the `input-leap` executable into the Privacy & Security -> Accessibility menu. 

It's pretty trivial but adding screenshot for funsies.

<img width="1160" alt="image" src="https://github.com/user-attachments/assets/ded12976-2b58-42d7-9e6b-c442df991b40">

**Comment by zgastley** [comment]
The same issue was reported for [Barrier](https://github.com/debauchee/barrier/issues/1322). Marked as `Closed` but it doesn't look like code changes were made.

**Comment by toshmukhamedov** [comment]
+

**Comment by kirichkov** [comment]
For me the workaround didn't work on macOS Sequioa as server. I did get the prompt to allow InputLeap for Accessability, did allow it, restarted the application, but still in the log I the same error message repeat. Clicking on "Stop" wouldn't stop the server process and only right-clicking and clicking "Quit" fixed the "restart loop".

**Comment by Laephis** [comment]
> For me the workaround didn't work on macOS Sequioa as server. I did get the prompt to allow InputLeap for Accessability, did allow it, restarted the application, but still in the log I the same error message repeat. Clicking on "Stop" wouldn't stop the server process and only right-clicking and clicking "Quit" fixed the "restart loop".
> 
> **UPDATE**: What fixed the issue for me was opening the Application bundle and dragging and dropping the `/Applications/InputLeap.app/Contents/MacOS/input-leap` binary to `System Settings > Privacy & Security > Accessability` list and allowing it to control the computer.

Thanks, this fixed the issue for me as well.

**Comment by kirichkov** [comment]
> connection works with mouse but i'm not getting any feedback from my keyboard @Laephis @kirichkov ... does the keyboard require something else?

I had no issues, so can't give any feedback.

**Comment by shymega** [comment]
Hi,

Please avoid bumping the issue when unnecessary.

If you also experience the issue, kindly react to the issue with `:+1:`, or if you want to find out when the issue will be resolved, please do not bump the issue, but _instead_ subscribe to the issue using the button on the right-hand side.

As for the fix @kirichkov posted, I believe that has resolved the issue, so will close this issue now.

**Comment by shymega** [comment]
> connection works with mouse but i'm not getting any feedback from my keyboard @Laephis @kirichkov ... does the keyboard require something else?

This is a different issue.

**Comment by below43** [comment]
I'm not sure if this helps at all, but i just installed Input Leap on my mac after using Barrier and still get this issue.

It shows up in the accessibility settings, and is enabled, but I still get this error as per this ticket (MacOS Sequoia 15.1.1; 3.0.2-release-release-7e5889dc)

**Comment by rhicore** [comment]
still met this problem in v3.0.3 on Sequoia 15.5
there are two different items in accessbility list, i think it's worth to fix this small problem

<img width="475" height="208" alt="Image" src="https://github.com/user-attachments/assets/be78eaf0-be98-45c4-b11f-53e5ea71d5e7" />

**Comment by shymega** [comment]
Hi,

Please avoid bumping the issue when unnecessary.

If you also experience the issue, kindly react to the issue with `:+1:`, or if you want to find out when the issue will be resolved, please do not bump the issue, but _instead_ subscribe to the issue using the button on the right-hand side.

**Comment by GollyJer** [comment]
+1

**Comment by qn1213** [comment]
Resolved successfully using the above method.
Tahoe 26.5

> The fix in OP's post works for me. Settings > Privacy and Security > Accessibility. Click the plus (+) at bottom left of window and click+drag /Applications/InputLeap.app/Contents/MacOS/input-leap file into that window. Server immediately started.
