### ISSUE TITLE
Wrong Key gets transmitted (Windows to Mac)

### ISSUE THREAD

**Issue by colenio-mhe** [input-leap/input-leap#2077]
### What happened?

Hey everyone.

I just upgraded from Barrier 2.4.x to InputLeap 3.0.3 it seems like mostly everything is working but strangely when im on my Mac and Type . (dot) I get a , (comma).

My Windows 11 PC is the Server and the Mac is the Client.

After that I checked other Keys to:

| Key Pressed | Key on Mac (Numlock On)| Key on Mac (Numlock Off)|
| -------- | ------- | ------- |
| . | ,   | . (expected)|
| #| 3   | # (expected) |
| alt-gr + <|  \|  (expected) | 7 |

I wrote (expected) to the key that should have been send (regardless of numlock on/off)

Using a Keyboard tester I saw that it seems that most keys send are the numpad ones. So pressing 1234... on the main row activate the numpad ones.. Pressing . activates the , on the numpad (german layout). After disabling num on the Keyboard it works as expected, obvioulsy numpad now doesnt work. Numpad fix didn't change anything for me.

Is this a bug or am i missing some setting?

Thanks!

### Version

v3.0.2

### If applicable, where did you install Input Leap from?

GitHub binaries

### What OSes are you seeing the problem on? (Check all that apply)

Windows, macOS

### What OS versions are you using?

Windows 11 (Server)
macOS 15.1 (M1) (Client)

### Any other information

German Keyboard Layout

**Comment by matthewtai** [comment]
+1
Win11 Server, macOS client
Experiencing more or less the same thing

EN(US) on Win11 > EN (US) on macOS Sonoma 14.7

Tried both v3.02 and v3.01, same issue, seems to be triggered when Num Lock is on

**Comment by c2ho** [comment]
More or less the same here with a Windows 11 server-side and macOS 15.0.1 client-side on [7e5889d](https://github.com/input-leap/input-leap/commit/7e5889dc6fc907a0dd218d94623378cc53417cb2)

I am using the german layout on all sides.

Also some other keys or combinations don't work, I'll try to add them if I encounter them as I do not remember them after the weekend :smile:

**Comment by colenio-mhe** [comment]
It nearly does but if you disable NumPad you cant make | anymore, you then get a 7.

right now I downgraded to barrier 2,4 on my mac that fixed it. 
So Inputleap 3.0.2 on Windows (Server) to barrier 2.4 on macOS (Client)

**Comment by taylankasap** [comment]
> E.g. `=` cannot be registered

`=` sends backspace for me 😄

**Comment by Shira-3749** [comment]
It's even more broken with a czech keyboard layout 😞 

- the ";" key sends "ů" instead
- the "=" key does nothing
- shift + ¨ should be "'" but sends "§"
- basically all alt AltGr (right alt key) combinations are sent wrong, examples:
  - AltGr + w should send "|", but sends "\"
  - AltGr + f should send "[", but sends "ú"
  - AltGr + g should send "]", but sends ")"
  - AltGr + b should send "{", but sends "í"
  - AltGr + n should send "}", but sends "é"
  - AltGr + c should send be "&", but sends "ý"
  - AltGr + e should send "€", but sends "r"

**Comment by surajsamal00** [comment]
> > E.g. `=` cannot be registered
> 
> `=` sends backspace for me 😄
> 
> Edit: It's not backspace, it's the `Clear` key https://deskthority.net/wiki/Clear_key
> 
> Edit 2: Just noticed F13-F16 keys started working on the MacOS client when this bug happens. They were **not** working before.
> 
> Edit 3: Not sure at what point this started but now the `=` key is not working on the linux **server** and is working on the macos client.


Had the same clear key instead of = key issue. Try turning numlock (on or off) then using the = key, it worked for me
