### ISSUE TITLE
Two Bugs about This app.

### ISSUE THREAD

**Issue by ZhuShaoQiang** [input-leap/input-leap#2092]
### What happened?

I have found out two bugs:
1. the symbol "=" cannot pass from windows11 to mac(M1, Sequoia 15.1)。
2. when I am using this and sharing my Windows' keyboard with my Mac, my Mac sometimes cannot input Chinese, even during my typing process, But if I shut the input-leap down, the Mac can input Chinese immediately.(This bug existed when I was using Barrier's latest version)。

### Version

v3.0.2

### If applicable, where did you install Input Leap from?

Github

### What OSes are you seeing the problem on? (Check all that apply)

Windows, macOS

### What OS versions are you using?

Windows:
版本	Windows 11 专业版
版本号	24H2
安装日期	‎2024/‎10/‎22
操作系统版本	26100.2314
体验	Windows Feature Experience Pack 1000.26100.32.0

Mac:
MacBook Air
Apple M1
OS version: 15.1 (24B83)

**Comment by shymega** [comment]
Please open two separate bugs, combining them into the same bug report makes it harder to track.
