### ISSUE TITLE
client connects, but connot move mouse over to other computer.

### ISSUE THREAD

**Issue by kaosbeat** [input-leap/input-leap#2121]
### What happened?

I installed the 3.0.2 release ubuntu 24.10 version on an ubuntu client and the latest debian release version on a debian 12 host.
The debian is acting as a server. Ubuntu asks for to "Allow remote Interaction" as soon as I click start, which I accept.

In the server log I can see the client connecting succesfully, but no mouse movement to othe rcomputer is possible

### Version

v3.0.2

### Git commit hash (if applicable)

2641bc502e16b1fb7372b43e94d4b894cbc71279

### If applicable, where did you install Input Leap from?

client, release package for 3.02 ubuntu 24.10
server, both debian 12 release apckage and built from source. Both have same behavior

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

wayland on both client/server  In the release file the package is stated to support wayland. When building from source I cannot find any option to enable wayland support, so I assume it is enabled by default?

### What OS versions are you using?

ubuntu24.10 wayland (client)
debian 12 wayland (server)

### Relevant log output

```shell
[2024-12-09T14:54:02] INFO: log level: INFO
started server (IPv4/IPv6), waiting for clients
	~/input-leap/src/lib/inputleap/ServerApp.cpp,568

[2024-12-09T14:54:02] NOTE: accepted client connection
	~/input-leap/src/lib/server/ClientListener.cpp,137
[2024-12-09T14:54:02] NOTE: client "laptop" has connected
	~/input-leap/src/lib/server/Server.cpp,293
```

### Any other information

I have exact same behaviour on both source built and debian package.
this all used to work fine (before wayland?)

**Comment by shymega** [comment]
You need `xdg-desktop-portal`,  `libportal` and the XDG Portals for your DE installed with the `RemoteControl` and `InputCapture`, as well as `libei` installed on both Wayland machines. I suspect your Debian install is lagging.

Not much we can do here...

**Comment by kaosbeat** [comment]
Ok 

I tried manually upgrading but quickly ran into dependency hell
libei1 would install fine but the desktop portals depend on too many packages


Thanks for pointing out the reason, I feel that this should be reported by the server on install though.

**Comment by shymega** [comment]
It's not easy to report, if at all possible - especially on install. Yes, we could run runtime checks. But I'm going to close this issue now.
