### ISSUE TITLE
Client connecting to server successfully, but no keyboard/mouse use on client from the server.

### ISSUE THREAD

**Issue by ziferius** [input-leap/input-leap#2136]
### What happened?

Server: Fedora 40 v3.0.2-release-release-000000000 using WayLand, called 'starbook'
Client: Raspberry Pi 4 (armhf 32-bit) 3.0.2-'git-2024-12-12-00bdd5c0' using x11 called 'raspberrypi'

I cloned the github repo, install the libs needed and compiled the server & client of input-leap.  There aren't readily available Qt6 compiled for armhf/32-bit of Rasp Pi OS (debian bookworm/12) so I did not compile the GUI.

After false starts of connecting:
- Verifying the network connectivity with openssl s_client
- Then copying the server fingerprint from Local.txt on the server to TrustedServers.txt on the client
- the client was getting an error, '[Authorization required, but no authorization protocol specified', so ran 'xhost starbook' on the client.
- 
The log on 'starbook' (the server) shows that the raspberrypi (the client) is connected successfully.

However, when I attempt to go over to the raspberrypi screen, nothing happens.  On the 'starbook' (server), I get the system tray notification icon, I guess from wayland, that it is getting keyboard/mouse info from Wayland.  The log even shows it going over to the screen.

I'm not sure what to do next.

Any assistance is appreciated.

[client-raspberrypi.log](https://github.com/user-attachments/files/18219747/client-raspberrypi.log)
[server-starbook.log](https://github.com/user-attachments/files/18219748/server-starbook.log)

### Version

From Git HEAD or commit (specify below)

### If applicable, where did you install Input Leap from?

Server: Fedora 40 repos
Client: Github, downloaded the repo and compiled.

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Server: Wayland
Client: X11

### What OS versions are you using?

Server: Fedora 40, x86_64
Linux starbook 6.11.10-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Nov 23 00:53:13 UTC 2024 x86_64 GNU/Linux

Client: Raspberry Pi 4 - Raspberry Pi OS: debian 12 bookworm
Linux starbook 6.11.10-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Nov 23 00:53:13 UTC 2024 x86_64 GNU/Linux

** Rasbberry Pi uses an aarm64 kernel but a 32-bit build environment...... here's the dpkg-architecture --list output:
sudo dpkg-architecture --list
DEB_BUILD_ARCH=armhf
DEB_BUILD_ARCH_ABI=eabihf
DEB_BUILD_ARCH_BITS=32
DEB_BUILD_ARCH_CPU=arm
DEB_BUILD_ARCH_ENDIAN=little
DEB_BUILD_ARCH_LIBC=gnu
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=arm
DEB_BUILD_GNU_SYSTEM=linux-gnueabihf
DEB_BUILD_GNU_TYPE=arm-linux-gnueabihf
DEB_BUILD_MULTIARCH=arm-linux-gnueabihf
DEB_HOST_ARCH=armhf
DEB_HOST_ARCH_ABI=eabihf
DEB_HOST_ARCH_BITS=32
DEB_HOST_ARCH_CPU=arm
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_LIBC=gnu
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=arm
DEB_HOST_GNU_SYSTEM=linux-gnueabihf
DEB_HOST_GNU_TYPE=arm-linux-gnueabihf
DEB_HOST_MULTIARCH=arm-linux-gnueabihf
DEB_TARGET_ARCH=armhf
DEB_TARGET_ARCH_ABI=eabihf
DEB_TARGET_ARCH_BITS=32
DEB_TARGET_ARCH_CPU=arm
DEB_TARGET_ARCH_ENDIAN=little
DEB_TARGET_ARCH_LIBC=gnu
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=arm
DEB_TARGET_GNU_SYSTEM=linux-gnueabihf
DEB_TARGET_GNU_TYPE=arm-linux-gnueabihf
DEB_TARGET_MULTIARCH=arm-linux-gnueabihf

### Relevant log output

```shell
Attached log files from the server and client above in the 'what happened' section.
```

**Comment by ziferius** [comment]
Forgot the git hash of the version I compiled for the raspberry pi: b0c0b42b

**Comment by ziferius** [comment]
I am mistaken; Raspberry Pi OS (debian 12/bookworm based) uses the Wayland compositor 'wayfire'.  [Raspberry Pi news](https://www.raspberrypi.com/news/a-new-release-of-raspberry-pi-os/#:~:text=With%20the%20release%20of%20Bookworm,X%20on%20lower%2Dpowered%20models.)

**Comment by ziferius** [comment]
So I'm closing this.  I've learned a bit more of the build process (IE, I read more of the wiki than I did).......as compiled for Fedora and things did not work as expected... It seems I forgot to enable libei and libportal and the Fedora compile did not work as the installed rpm package did until I did so. 

On the raspberry pi, I did the same; but when I went to install libportal -- I had to backport it from 'testing' to bookworm.  I started to do the same for libportal, but having numerous unmet dependencies, one of them is 'meson' and will not compile on armhf.  So I can't build libportal to v.08+ on rasberrypi at this time..... so I'm closing this.

Love your software BTW!

**Comment by ziferius** [comment]
oops; need to close

**Comment by shymega** [comment]
You have closed it. But FYI, we don't support any wlroots-based WMs, or indeed in general, other than KDE/GNOME. Also, the Pi 4 supports arm64, which will be much easier for you.

**Comment by ziferius** [comment]
I believe bookworm does not have in the underbelly, libportal-dev.  So I'm
exploring backporting it from trixie (debian 13 which isn't released for
another year or two).  I used armhf simply because it was recommended as
the most compatible w/ Project OutFox / Stepmania... using my rpi as a
Dance Dance Revolution player.  My plan is to once this is working, submit
an update for the Wiki for a Debian/Rasp Pi section to add.

I'll have to lookup what wlroots-based Window Manager are :)

**Comment by shymega** [comment]
Wayfair is wlroots-based, so you can't use Input Leap with it.
