### ISSUE TITLE
New Branding

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#215]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/215
> 
> Issue created on: 2018-12-30 by @mcdviii
> Issue last updated on: 2021-05-05

I've drawn up some new branding for the project if anyone is interested. You can find it below:

https://i.imgur.com/iIMDoKm.png
https://imgur.com/VwtW45A.png

The only issue is that the fonts I used are Futura & Hiragino Maru Gothic, respectively. I'm not sure if that might create licensing problems.

---

> Commented on: 2018-12-30 by @AdrianKoshka

Something about how smooth `Barrier` is bothers me, and I can't quite pin-point why.

![barrier](https://i.imgur.com/VwtW45A.png)

---

> Commented on: 2018-12-30 by @AdrianKoshka

Btw, https://fonts.google.com/ is a good resource for finding fonts and their license(s).

---

> Commented on: 2019-02-04 by @Ashark

What is the meaning of striked out zero?

---

> Commented on: 2019-02-04 by @AdrianKoshka

No barriers I would assume?

---

> Commented on: 2019-02-14 by @Ashark

I think striked out zero is no such informative.
I saw some good pictures, that make you understand the software idea, but they look too detailed to be an icon:
https://www.groovypost.com/wp-content/uploads/2012/08/image52.png
http://saisa.eu/blogs/Guidance/wp-content/uploads/2015/02/synenergy2.png
https://techvorm.com/wp-content/uploads/2017/03/Synergy-Banner.png
https://allusefulinfo.com/wp-content/uploads/2015/12/input-director.jpg
https://art-u3.infcdn.net/articles_uploads/2/2848/Main.jpg

Maybe rework something like this?
<img src="https://user-images.githubusercontent.com/22634975/52791378-e0129100-3079-11e9-970a-369f46e9a958.png" width="200">

---

> Commented on: 2019-02-16 by @mcdviii

Good thoughts @Ashark. The icon should probably communicate what the project provides instead of what it doesn't. I see what you're going for with your examples but I agree that they are too complex for a good icon. I wonder if we could come up with a dead-simple piece of iconography that symbolizes sharing resources.

I'm thinking something like this, but with a mouse:

https://pngtree.com/free-icon/the-icon-shared-resources_443158

The other thing we could do is symbolize one mouse or keyboard. Like 1 x ${icon of mouse or keyboard}, or something similar.

---

> Commented on: 2019-02-16 by @Ashark

Maybe somehow create a "keyboard router" icon? Just a dirty preview:
![km router](https://user-images.githubusercontent.com/22634975/52906365-60441c80-325b-11e9-90bd-e8cbdb8ae27e.png)
It may look much better (for [example](https://www.cisco.com/c/es_mx/support/routers/cloud-services-router-1000v-series/tsd-products-support-series-home/_jcr_content/module-display-selector/small-product-image.img.jpg/1496310047721.jpg))
Or create a keyboard itself as a router box, any thoughts?

---

> Commented on: 2019-02-17 by @AdrianKoshka

How many people actually know what that router icon box means? :P

---

> Commented on: 2019-02-17 by @Ashark

Well, maybe they will know something new. It at least makes sense.

---

> Commented on: 2019-02-17 by @AdrianKoshka

> Well, maybe they will know something new. It at least makes sense.

They won't, and it won't.

---

> Commented on: 2019-02-17 by @Ashark

Several another ideas:
As suggested earlier, palm km share:
![palm km share](https://user-images.githubusercontent.com/22634975/52907019-b3bd6700-3269-11e9-91a1-e89c94a4c248.png)
Pipe km share (like in windows folder share):
![pipe km share](https://user-images.githubusercontent.com/22634975/52907025-d485bc80-3269-11e9-96c8-7f81f0b2668d.png)
Fork km share (like usb symbol, still too detailed):
![fork km share](https://user-images.githubusercontent.com/22634975/52907027-e5363280-3269-11e9-8d12-3c18bf8e44e2.png)

---

> Commented on: 2021-05-05 by @dreamer

Bumping up the thread, because Barrier definitely needs a nicer icon ;)

**Comment by sithlord48** [comment]
@shymega   Invalid? We have new branding and are no longer barrier

**Comment by shymega** [comment]
Not invalid, but it no longer needs to be opened. You are correct.

Closing as resolved.
