### ISSUE TITLE
Update linux build instruction on wiki for Fedora

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#254]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/254
> 
> Issue created on: 2019-02-15 by @Nanoseb
> Issue last updated on: 2019-02-16

Hi,
Sorry this is not an issue but more a pull request for the wiki.
I have just compiled and installed barrier on Fedora and hence I had to adapt the package list needed  from the one on the wiki. Here is the list I used:

```
sudo dnf install git cmake  gcc-c++ xorg-x11-server-devel \
                 libcurl-devel avahi-compat-libdns_sd-devel \
                 libXtst-devel qt5 qt5-devel openssl-devel
```
Maybe someone can update the wiki and add this?

Thank you all for this fork,

Seb

---

> Commented on: 2019-02-16 by @AdrianKoshka

Yep, no problem!

---

> Closed on: 2019-02-16 by @AdrianKoshka

**Comment by whot** [comment]
fwiw, might be worth linking to the Fedora spec file since that is less likely to go stale than a wiki and has the definitive list of dependencies: https://src.fedoraproject.org/rpms/barrier/blob/rawhide/f/barrier.spec

**Comment by shymega** [comment]
Yes, but that's an external link, and subject to change. It also doesn't have the command one-liner, so I see the wiki's approach is inherently preferable.
