### ISSUE TITLE
Mouse cursor invisible in Linux/Gnome 3.30.2 on Wayland client

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#358]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/358
> 
> Issue created on: 2019-07-09 by @LIII-XXII
> Issue last updated on: 2021-10-02

### Operating Systems ###

Server: Windows 10 1809 17763.557

Client: Gentoo / Gnome 3.30.2 on Wayland

### Barrier Version ###

2.1.2 from pixlra overlay: qt5, openSSL

### Steps to reproduce bug ###

The mouse cursor does not appear on the Linux/Wayland client.
I can click things, type text, etc, but the mouse cursor is not visible...

### Other info ###

I saw that there is a possible workaround by enabling mouse cursor even with touch screens in Gnome, but the setting does not seem to be there in my Gnome version.

```
gsettings set org.gnome.settings-daemon.plugins.cursor active false
No such schema “org.gnome.settings-daemon.plugins.cursor”
```

---

> Commented on: 2019-07-09 by @AdrianKoshka

There is no wayland support unfortunately.

---

> Commented on: 2019-07-19 by @LIII-XXII

I have XWayland libraries though, which claim to be downwards compatible with X server interfaces. I believe the mouse cursor not being visible is actually caused by some gnome usb tablet settings disabling the cursor icon, because everything works besides that.

---

> Commented on: 2019-07-19 by @LIII-XXII

is something from Barrier supposed to show up in xinput? It's a laptop, I have a mouse and a touchpad.
This is the output with the Barrier client connected to a server.
```
xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ xwayland-pointer:17                     	id=6	[slave  pointer  (2)]
⎜   ↳ xwayland-relative-pointer:17            	id=7	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ xwayland-keyboard:17                    	id=8	[slave  keyboard (3)]
```

---

> Commented on: 2021-04-11 by @frohro

I just installed Ubuntu 21.04, and it uses Wayland by default.  I noticed this behavior too.  You can click on things, and it works.  It is just you cannot see the position of the mouse cursor.  For example, some programs change the display when the mouse hovers over something.  You can click on that and it work fine.  When I saw "no Wayland support," I didn't expect it to look so very close to working.  I can even type things just fine.  It is just difficult to figure out what will receive the text.

---

> Commented on: 2021-10-02 by @pangyuteng

I updated from Ubuntu 20.04 to 21.04, cursor and keyboard both do not work (cannot click, cannot type), but barrier can detect the cursor coming into the client - based on the logs.

Below is one solution for those using Ubuntu and is not constrainted to Wayland.
You could just opt for Xorg during login - during the password prompt, click `Ubuntu on Xorg` at the bottom right corner. cheers.

---

> Closed on: 2019-07-09 by @AdrianKoshka

**Comment by benmordecai** [comment]
I am having the same issue on Gnome 45.1 on Wayland with the AUR install of input-leap-git as the client. I do have libei installed.
