### ISSUE TITLE
cmake compile error 

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#844]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/844
> 
> Issue created on: 2020-08-19 by @glynnelson
> Issue last updated on: 2020-09-27

### Operating Systems ###

Server: macOS 10.15.6

Client: OpenSuse15.2

### Barrier Version ###

2.3.3

### Steps to reproduce bug ###

clone/download barrier and attempt to compile on OpenSuse15.2 (only 2.3.2 exists as a pre-build as far as I can find).    Two errors running clean_build.sh as follows:

1st error: -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed

2nd error:
CMake Error at src/test/CMakeLists.txt:23 (add_library):
  Cannot find source file:
    ../../ext/gtest/src/gtest-all.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at src/test/CMakeLists.txt:24 (add_library):
  Cannot find source file:
    ../../ext/gmock/src/gmock-all.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at src/test/CMakeLists.txt:23 (add_library):
  No SOURCES given to target: gtest

CMake Error at src/test/CMakeLists.txt:24 (add_library):
  No SOURCES given to target: gmock

CMake Generate step failed.  Build files cannot be regenerated correctly.

I've installed cmake and cmake-all from Suse repos, plus gmake and gtest and the dependencies liste din the rpm folder text file.  It looks like the cmake version (3.17.0) doesn't include these libraries?

Is there a way around this to compile for this OS?

**READ ME, DELETE ME**: Try to be succinct. If your bug is intermittent, try and describe what you're doing when it happens most.

1. Click things.
2. Type things.
3. Bug occurs.
4. ... 

### Other info ###

* When did the problem start to occur? When I tried to compile barrier myself to match the version running on the MacOS
* Is there a way to work around it? No/Yes, Don't know- get cmake3 from somewhere else???  Or alter the build.sh file to dela with this dependency?
* Does this bug prevent you from using Barrier entirely? Yes

Put anything else you can think of here.

---

> Commented on: 2020-08-19 by @shymega

If you're building from Git, you need to initialise the submodules for gtest and gmock.

On this date - Wed, Aug 19, 2020 at 05:52:10AM -0700, glynnelson wrote:
> ### Operating Systems ###
>
> Server: macOS 10.15.6
>
> Client: OpenSuse15.2
>
>
> ### Barrier Version ###
>
> 2.3.3
>
> ### Steps to reproduce bug ###
>
> clone/download barrier and attempt to compile on OpenSuse15.2 (only 2.3.2 exists as a pre-build as far as I can find).    Two errors running clean_build.sh as follows:
>
> 1st error: -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
>
> 2nd error:
> CMake Error at src/test/CMakeLists.txt:23 (add_library):
>   Cannot find source file:
>     ../../ext/gtest/src/gtest-all.cc
>
>   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
>   .hpp .hxx .in .txx
>
> CMake Error at src/test/CMakeLists.txt:24 (add_library):
>   Cannot find source file:
>     ../../ext/gmock/src/gmock-all.cc
>
>   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
>   .hpp .hxx .in .txx
>
> CMake Error at src/test/CMakeLists.txt:23 (add_library):
>   No SOURCES given to target: gtest
>
> CMake Error at src/test/CMakeLists.txt:24 (add_library):
>   No SOURCES given to target: gmock
>
> CMake Generate step failed.  Build files cannot be regenerated correctly.
>
> I've installed cmake and cmake-all from Suse repos, plus gmake and gtest and the dependencies liste din the rpm folder text file.  It looks like the cmake version (3.17.0) doesn't include these libraries?
>
> Is there a way around this to compile for this OS?
>
>
> **READ ME, DELETE ME**: Try to be succinct. If your bug is intermittent, try and describe what you're doing when it happens most.
>
> 1. Click things.
> 2. Type things.
> 3. Bug occurs.
> 4. ...
>
> ### Other info ###
>
> * When did the problem start to occur? When I tried to compile barrier myself to match the version running on the MacOS
> * Is there a way to work around it? No/Yes, Don't know- get cmake3 from somewhere else???  Or alter the build.sh file to dela with this dependency?
> * Does this bug prevent you from using Barrier entirely? Yes
>
> Put anything else you can think of here.
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/debauchee/barrier/issues/844

--
Kind regards,
Dom Rodriguez (shymega)

---

> Commented on: 2020-09-27 by @mariolpantunes

I have the same error.
The solution is not valid since I am trying to compile the release tarball, and there is no git folder.

---

> Closed on: 2020-08-22 by @p12tic

**Comment by shymega** [comment]
No, but the issue could merely just be the tarball. You can download from Git, checkout the release, and initialise the submodules for now. It really depends how you build Input Leap.
