### ISSUE TITLE
how to switch ip address？

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#876]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/876
> 
> Issue created on: 2020-09-19 by @lyolve
> Issue last updated on: 2020-09-22

I use zerotier to create a virtual local area network，and the ip is 10.147.17.x，there is correct ip address shown on the interface of Barrier，but only 192.168.1.x is bolded，can i switch communication address from 192.168.1.x to 10.147.17.x ？

---
English is not my mother tongue，sorry~

---

> Commented on: 2020-09-21 by @shymega

You mean the bind address?

---

> Commented on: 2020-09-22 by @lyolve

Thank you for your reply.
I've worked it out.
It seems that I misunderstood the meaning of the bold fonts.
![image](https://user-images.githubusercontent.com/43743367/93838571-acb7cf80-fcbc-11ea-910a-d281393f8fb2.png)

---

> Closed on: 2020-09-22 by @lyolve

**Comment by jsheperd** [comment]
I had the same issu and found this closed issue.
It taken to me some minutes to find the mentioned settings window.

The settings panel is accessible from the main menu -> change settings point.
