### ISSUE TITLE
Feature request: Upgrade QT version for Windows

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#890]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/890
> 
> Issue created on: 2020-09-28 by @ItachiSan
> Issue last updated on: 2020-09-28

Hi everyone,

I feel the QT version used looks quite outdated, with this look-and-feel:
![photo_2020-09-28_14-52-48](https://user-images.githubusercontent.com/1223421/94434592-55bd6900-019a-11eb-94f6-b6a69b57be0f.jpg)
This is the official Barrier 2.3.3.

This is the code in the *master* branch, built with QT 5.12.5:
![photo_2020-09-28_14-52-52](https://user-images.githubusercontent.com/1223421/94434683-7685be80-019a-11eb-88b2-7126f4ff87eb.jpg)

I personally believe it looks quite better. 😄 

If this request is consider helpful / useful, I can try to hack my way through in order to get the proper QT version to be used 😄

**Comment by sithlord48** [comment]
Please close this is no longer valid we use Qt 5.15 for windows currently and could use Qt6 as well

**Comment by shymega** [comment]
Agreed. This is a relic from the migration bot.
