### ISSUE TITLE
Barrier without admin rights, is it even possible ?

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#959]
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/959
> 
> Issue created on: 2020-11-24 by @ChristopheClaustre
> Issue last updated on: 2020-12-25

Hi everyone,

I want to use Barrier in an environment where not all users have admin rights.
Is there a way to have a barrier version (and installer) without admin rights ?
Is it even possible ? At least for client ?

## Configuration

- Server: Windows 7 64b Pro with admin rights, connected by ethernet
- Client: Windows 10 64b Pro without admin rights, connected by WIFI
- Barrier version: v2.3.3

My rooter see both computers.

## What I tried

I installed it on server without any problems, then zip and send the installation folder to my client.
The result is that this _nasty_ version on client keep blocking on "Barrier is starting.", while spamming in the log the following errors:
```
[2020-11-24T15:32:12] ERROR: ipc connection error, connection refused
[2020-11-24T15:32:13] INFO: connecting to service...
[2020-11-24T15:32:15] ERROR: ipc connection error, connection refused
[2020-11-24T15:32:16] INFO: connecting to service...
[2020-11-24T15:32:18] ERROR: ipc connection error, connection refused
[2020-11-24T15:32:19] INFO: connecting to service...
```
It spams those errors even when I "Stop" the connection.
I suppose that "connecting to service" is specific to the client computer and not dependent of server's barrier potential dysfunction ^^"

Hope someone can help me ;)

---

> Commented on: 2020-12-06 by @albertony

By using the command-line versions (barrier**c**.exe and barrier**s**.exe), documented [here](https://github.com/debauchee/barrier/wiki/Command-Line) you will be able to run both client and server without admin. There are some limitations when running barrier without admin, e.g. you will loose "control" if any elevated windows are active or if UAC prompts appear, but other than that it works.

I have a [pull requestion](https://github.com/debauchee/barrier-wiki/pull/5) for the wiki page which describes the command line version a bit more, with added details about minimal copy install of command line client/server, configuring local configuration, manually generating encryption certificate etc. See https://github.com/albertony/barrier-wiki/blob/local_config/Command-Line.md.

---

> Commented on: 2020-12-07 by @ChristopheClaustre

Thanks for your answer. It helped a lot :)

My problem seems to be that my client can't use OpenSSL without admin rights and on this computer i can't have them. So I disabled ssl encryption on server and now it's working ! Thank you for your help.

By the way, you should consider distributing command line only installer ;)
It's note really user-friendly to install on another computer and transfer the install folder.

Thanks for all your hard work since synergy became paying ;)

---

> Commented on: 2020-12-07 by @albertony

> By the way, you should consider distributing command line only installer ;)

I agree!

> It's note really user-friendly to install on another computer and transfer the install folder.

In the meantime, you can extract all files from the installer using command line utility [innounp](http://innounp.sourceforge.net/), and then create your own copy-install package without installing it somewhere first.

> My problem seems to be that my client can't use OpenSSL without admin rights.

You can't run the openssl executable, to generate certificate? Or barrier executable can't use openssl libraries? If it is the first, I found that when creating cert openssl wants to create file `C:\.rnd`, which requires admin, but can be avoided by setting environment variable RANDFILE, as in my example here: https://github.com/albertony/barrier-wiki/blob/local_config/Command-Line.md#generating-certificate-and-fingerprint

---

> Commented on: 2020-12-07 by @ChristopheClaustre

> > It's note really user-friendly to install on another computer and transfer the install folder.
>
> In the meantime, you can extract all files from the installer using command line utility innounp, and then create your own copy-install package without installing it somewhere first.

Didn't know this software, seems useful but still it is not really user-friendly ^^"

> You can't run the openssl executable, to generate certificate? Or barrier executable can't use openssl libraries? If it is the first, I found that when creating cert openssl wants to create file C:\.rnd, which requires admin, but can be avoided by setting environment variable RANDFILE, as in my example here: https://github.com/albertony/barrier-wiki/blob/local_config/Command-Line.md#generating-certificate-and-fingerprint

Okay, I spoke too soon ^^".
The server part was okay as I am using UI version ^^" (I have admin rights here).
On the client, I updated my TrustedServers.txt and now it's working with encryption.

But still it doesn't work with UI on client. I get the same error than on my first post. Don't know why.

---

> Commented on: 2020-12-24 by @plessbd

I know this is closed, but there is an easier way to get the programs without extracting the installer.
Use the Azure pipelines

1. https://dev.azure.com/debauchee/Barrier/_build?definitionId=1&_a=summary
1. click on one of the builds
1. Under Related click the second item (looks like a package ans says # published)
1. Then I use windows release

This will give you a zip file.

---

> Commented on: 2020-12-25 by @albertony

True. I am considering those beta builds, though.

---

> Closed on: 2020-12-07 by @ChristopheClaustre

**Comment by flamecopper** [comment]
@albertony

Yes I have confirm that the following methods work fine perfectly.

`By using the command-line versions (barrierc.exe and barriers.exe), documented [here](https://github.com/debauchee/barrier/wiki/Command-Line) you will be able to run both client and server without admin. There are some limitations when running barrier without admin, e.g. you will loose "control" if any elevated windows are active or if UAC prompts appear, but other than that it works.`
